export type { LearnTrailData, LearnSystem, LearnTrailItem, LearnMiniCase, LearnQuestion, LearnBridge, LearnSection } from "./types";
export { trilhaHipoxemia } from "./trilhas/hipoxemia";

import type { LearnSystem } from "./types";

export const LEARN_SYSTEMS: LearnSystem[] = [
  {
    id: "respiratorio",
    titulo: "Respiratório",
    descricao: "Hipoxemia, dispneia, sibilância, tosse, dor torácica e exame físico respiratório.",
    disponivel: true,
    href: "/learn/respiratorio",
    trilhas: [
      { id: "hipoxemia", titulo: "Hipoxemia", descricao: "SpO₂, oxigenação, ventilação, V/Q, shunt e mini-casos clínicos.", disponivel: true, href: "/learn/respiratorio/hipoxemia" },
      { id: "dispneia", titulo: "Dispneia", descricao: "Sensação de falta de ar: causas, gravidade e raciocínio.", disponivel: true, href: "/learn/respiratorio/dispneia" },
      { id: "sibilancia-e-broncoespasmo", titulo: "Sibilância e broncoespasmo", descricao: "Chiado, obstrução ao fluxo e padrões obstrutivos.", disponivel: true, href: "/learn/respiratorio/sibilancia-e-broncoespasmo" },
      { id: "tosse-e-febre", titulo: "Tosse e febre", descricao: "Síndromes respiratórias com tosse e febre.", disponivel: true, href: "/learn/respiratorio/tosse-e-febre" },
      { id: "dor-toracica-pleuritica", titulo: "Dor torácica pleurítica", descricao: "Dor pleurítica: causas e diagnóstico diferencial.", disponivel: true, href: "/learn/respiratorio/dor-toracica-pleuritica" },
      { id: "exame-fisico-respiratorio", titulo: "Exame físico respiratório", descricao: "Ausculta, percussão e semiologia do tórax.", disponivel: true, href: "/learn/respiratorio/exame-fisico-respiratorio" },
      { id: "gasometria-basica", titulo: "Gasometria básica", descricao: "Gasometria arterial: interpretação para iniciantes.", disponivel: true, href: "/learn/respiratorio/gasometria-basica" },
    ],
  },
  {
    id: "cardiovascular",
    titulo: "Cardiovascular",
    descricao: "Dor torácica, síncope, edema, arritmia, choque e sopros cardíacos.",
    disponivel: true,
    href: "/learn/cardiovascular",
    trilhas: [
      { id: "dor-toracica-e-sindrome-coronariana", titulo: "Dor torácica e SCA", descricao: "Dor torácica isquêmica e síndrome coronariana aguda.", disponivel: true, href: "/learn/cardiovascular/dor-toracica-e-sindrome-coronariana" },
      { id: "insuficiencia-cardiaca-congestao-e-edema", titulo: "Insuficiência cardíaca", descricao: "Congestão, dispneia, edema e IC descompensada.", disponivel: true, href: "/learn/cardiovascular/insuficiencia-cardiaca-congestao-e-edema" },
      { id: "sincope-palpitacoes-e-arritmias", titulo: "Síncope e arritmias", descricao: "Síncope, palpitações e arritmias básicas.", disponivel: true, href: "/learn/cardiovascular/sincope-palpitacoes-e-arritmias" },
      { id: "hipertensao-e-crise-hipertensiva", titulo: "Hipertensão e crise", descricao: "PA elevada, crise hipertensiva e lesão de órgão.", disponivel: true, href: "/learn/cardiovascular/hipertensao-e-crise-hipertensiva" },
      { id: "choque-e-perfusao", titulo: "Choque e perfusão", descricao: "Tipos de choque, hipoperfusão e instabilidade.", disponivel: true, href: "/learn/cardiovascular/choque-e-perfusao" },
      { id: "sopros-e-valvopatias-para-o-basico", titulo: "Sopros e valvopatias", descricao: "Sopros cardíacos e valvopatias essenciais.", disponivel: true, href: "/learn/cardiovascular/sopros-e-valvopatias-para-o-basico" },
      { id: "edema-e-circulacao-periferica", titulo: "Edema e circulação", descricao: "Edema, TVP e insuficiência venosa periférica.", disponivel: true, href: "/learn/cardiovascular/edema-e-circulacao-periferica" },
    ],
  },
  {
    id: "infectologia",
    titulo: "Infectologia",
    descricao: "Febre, sepse, dengue, infecções urinárias, meningite e antimicrobianos.",
    disponivel: true,
    href: "/learn/infectologia",
    trilhas: [
      { id: "febre-e-sindrome-infecciosa", titulo: "Febre e síndrome infecciosa", descricao: "Febre, síndrome infecciosa e raciocínio diagnóstico.", disponivel: true, href: "/learn/infectologia/febre-e-sindrome-infecciosa" },
      { id: "sepse-e-choque-septico", titulo: "Sepse e choque séptico", descricao: "Sepse, critérios SOFA e choque séptico.", disponivel: true, href: "/learn/infectologia/sepse-e-choque-septico" },
      { id: "dengue-e-arboviroses", titulo: "Dengue e arboviroses", descricao: "Dengue, febre, exantema e arboviroses tropicais.", disponivel: true, href: "/learn/infectologia/dengue-e-arboviroses" },
      { id: "infeccao-urinaria-e-pielonefrite", titulo: "ITU e pielonefrite", descricao: "ITU baixa, pielonefrite e antibioticoterapia.", disponivel: true, href: "/learn/infectologia/infeccao-urinaria-e-pielonefrite" },
      { id: "meningite-e-sinais-meningeos", titulo: "Meningite e sinais meníngeos", descricao: "Meningite, cefaleia e sinais meníngeos.", disponivel: true, href: "/learn/infectologia/meningite-e-sinais-meningeos" },
      { id: "antimicrobianos-basicos", titulo: "Antimicrobianos básicos", descricao: "Antibióticos essenciais: mecanismo e uso clínico.", disponivel: true, href: "/learn/infectologia/antimicrobianos-basicos" },
      { id: "tuberculose-e-tosse-cronica", titulo: "Tuberculose e tosse crônica", descricao: "Tuberculose e tosse crônica no ciclo básico.", disponivel: true, href: "/learn/infectologia/tuberculose-e-tosse-cronica" },
    ],
  },
  {
    id: "neurologia",
    titulo: "Neurologia",
    descricao: "Cefaleia, AVC, convulsão, rebaixamento, vertigem e exame neurológico.",
    disponivel: true,
    href: "/learn/neurologia",
    trilhas: [
      { id: "cefaleia-e-sinais-de-alarme", titulo: "Cefaleia e sinais de alarme", descricao: "Cefaleia, red flags e diagnóstico diferencial.", disponivel: true, href: "/learn/neurologia/cefaleia-e-sinais-de-alarme" },
      { id: "avc-e-deficit-focal", titulo: "AVC e déficit focal", descricao: "AVC, FAST e déficit neurológico focal.", disponivel: true, href: "/learn/neurologia/avc-e-deficit-focal" },
      { id: "crise-convulsiva", titulo: "Crise convulsiva", descricao: "Crise epiléptica: classificação e conduta.", disponivel: true, href: "/learn/neurologia/crise-convulsiva" },
      { id: "rebaixamento-de-consciencia", titulo: "Rebaixamento de consciência", descricao: "Causas e abordagem do rebaixamento de consciência.", disponivel: true, href: "/learn/neurologia/rebaixamento-de-consciencia" },
      { id: "vertigem-e-tontura", titulo: "Vertigem e tontura", descricao: "Vertigem, tontura e labirintopatia.", disponivel: true, href: "/learn/neurologia/vertigem-e-tontura" },
      { id: "exame-neurologico-essencial", titulo: "Exame neurológico", descricao: "Exame neurológico mínimo e interpretação.", disponivel: true, href: "/learn/neurologia/exame-neurologico-essencial" },
      { id: "dor-lombar-e-sinais-neurologicos", titulo: "Lombalgia e sinais neurológicos", descricao: "Dor lombar, bandeiras vermelhas e sinais neurológicos.", disponivel: true, href: "/learn/neurologia/dor-lombar-e-sinais-neurologicos" },
    ],
  },
  {
    id: "gastro-abdome",
    titulo: "Gastro/Abdome",
    descricao: "Dor abdominal, náuseas, icterícia, hemorragia digestiva e abdome agudo.",
    disponivel: true,
    href: "/learn/gastro-abdome",
    trilhas: [
      { id: "dor-abdominal", titulo: "Dor abdominal", descricao: "Dor abdominal: localização, padrão e hipóteses.", disponivel: true, href: "/learn/gastro-abdome/dor-abdominal" },
      { id: "nauseas-vomitos-e-diarreia", titulo: "Náuseas, vômitos e diarreia", descricao: "Síndrome gastrointestinal aguda.", disponivel: true, href: "/learn/gastro-abdome/nauseas-vomitos-e-diarreia" },
      { id: "ictericia", titulo: "Icterícia", descricao: "Icterícia: mecanismo, causas e investigação.", disponivel: true, href: "/learn/gastro-abdome/ictericia" },
      { id: "hemorragia-digestiva", titulo: "Hemorragia digestiva", descricao: "Hemorragia digestiva alta e baixa.", disponivel: true, href: "/learn/gastro-abdome/hemorragia-digestiva" },
      { id: "abdome-agudo", titulo: "Abdome agudo", descricao: "Abdome agudo cirúrgico e clínico.", disponivel: true, href: "/learn/gastro-abdome/abdome-agudo" },
      { id: "exame-fisico-abdominal", titulo: "Exame físico abdominal", descricao: "Palpação, ausculta e percussão abdominal.", disponivel: true, href: "/learn/gastro-abdome/exame-fisico-abdominal" },
      { id: "hepatologia-basica", titulo: "Hepatologia básica", descricao: "Fígado: função, disfunção e hepatopatia.", disponivel: true, href: "/learn/gastro-abdome/hepatologia-basica" },
    ],
  },
  {
    id: "semiologia-geral",
    titulo: "Semiologia Geral",
    descricao: "Anamnese, sinais vitais, dor, exame físico geral, comunicação e grupos especiais.",
    disponivel: true,
    href: "/learn/semiologia-geral",
    trilhas: [
      { id: "anamnese-clinica-estruturada", titulo: "Anamnese estruturada", descricao: "Anamnese: queixa, HDA e revisão de sistemas.", disponivel: true, href: "/learn/semiologia-geral/anamnese-clinica-estruturada" },
      { id: "sinais-vitais-e-gravidade", titulo: "Sinais vitais e gravidade", descricao: "Sinais vitais e reconhecimento de instabilidade.", disponivel: true, href: "/learn/semiologia-geral/sinais-vitais-e-gravidade" },
      { id: "dor-como-quinto-sinal", titulo: "Dor como quinto sinal", descricao: "Avaliação da dor, escalas e documentação.", disponivel: true, href: "/learn/semiologia-geral/dor-como-quinto-sinal" },
      { id: "exame-fisico-geral", titulo: "Exame físico geral", descricao: "Exame físico geral da cabeça aos pés.", disponivel: true, href: "/learn/semiologia-geral/exame-fisico-geral" },
      { id: "comunicacao-clinica", titulo: "Comunicação clínica", descricao: "Comunicação médico-paciente e relação terapêutica.", disponivel: true, href: "/learn/semiologia-geral/comunicacao-clinica" },
      { id: "pediatria-sinais-de-gravidade", titulo: "Pediatria: sinais de gravidade", descricao: "Reconhecimento de gravidade na criança.", disponivel: true, href: "/learn/semiologia-geral/pediatria-sinais-de-gravidade" },
      { id: "idoso-apresentacao-atipica", titulo: "Idoso: apresentação atípica", descricao: "Como o idoso apresenta doenças de forma diferente.", disponivel: true, href: "/learn/semiologia-geral/idoso-apresentacao-atipica" },
    ],
  },
  {
    id: "raciocinio-clinico",
    titulo: "Raciocínio Clínico",
    descricao: "Síndromes, hipóteses, priorização, exames, conduta e apresentação clínica.",
    disponivel: true,
    href: "/learn/raciocinio-clinico",
    trilhas: [
      { id: "sindromes-antes-de-diagnosticos", titulo: "Síndromes antes de diagnósticos", descricao: "Síndrome como primeiro passo do raciocínio clínico.", disponivel: true, href: "/learn/raciocinio-clinico/sindromes-antes-de-diagnosticos" },
      { id: "hipoteses-e-diagnostico-diferencial", titulo: "Hipóteses e diferencial", descricao: "Formular hipóteses e raciocínio diagnóstico.", disponivel: true, href: "/learn/raciocinio-clinico/hipoteses-e-diagnostico-diferencial" },
      { id: "priorizacao-e-erro-critico", titulo: "Priorização e erro crítico", descricao: "Priorizar e evitar erros em urgências.", disponivel: true, href: "/learn/raciocinio-clinico/priorizacao-e-erro-critico" },
      { id: "exames-que-mudam-conduta", titulo: "Exames que mudam conduta", descricao: "Solicitar exames que realmente mudam a decisão.", disponivel: true, href: "/learn/raciocinio-clinico/exames-que-mudam-conduta" },
      { id: "conduta-inicial-e-reavaliacao", titulo: "Conduta inicial e reavaliação", descricao: "Conduta inicial sistemática e reavaliação clínica.", disponivel: true, href: "/learn/raciocinio-clinico/conduta-inicial-e-reavaliacao" },
      { id: "erros-cognitivos-em-medicina", titulo: "Erros cognitivos em medicina", descricao: "Vieses cognitivos e erros diagnósticos comuns.", disponivel: true, href: "/learn/raciocinio-clinico/erros-cognitivos-em-medicina" },
      { id: "soap-e-apresentacao-clinica", titulo: "SOAP e apresentação clínica", descricao: "SOAP, raciocínio e apresentação para equipe.", disponivel: true, href: "/learn/raciocinio-clinico/soap-e-apresentacao-clinica" },
    ],
  },
];
