// ============================================================================
// soundsCatalog.ts — CATÁLOGO CANÔNICO de sons clínicos (HLS-CMDS).
// GERADO automaticamente por scripts/gen-sounds-catalog.mjs a partir de
// docs/LS.csv, docs/HS.csv e dos arquivos reais em public/HLS-CMDS/LS|HS.
// NÃO EDITAR À MÃO. Nenhuma correspondência é inventada: o tipo é sempre o do
// CSV; crepitações usam o mapa de código C→FC e G→CC (arquivos reais).
//
// Total: 100 sons (50 pulmonares + 50 cardíacos).
// Correspondência exata: 86 | código traduzido (C/G→FC/CC): 14.
// ============================================================================

export type ClinicalSoundCategory = "lung" | "heart";
export type ClinicalSoundMapping = "exact" | "translated-code";

export interface ClinicalSound {
  id: string;
  category: ClinicalSoundCategory;
  gender: "M" | "F";
  genderLabel: string;
  originalType: string;
  translatedType: string;
  location: string;
  locationLabel: string;
  csvId: string;
  audioFile: string;
  audioUrl: string;
  mappingType: ClinicalSoundMapping;
  sourceCsv: "LS.csv" | "HS.csv";
}

export const CLINICAL_SOUNDS: ClinicalSound[] = [
  {
    "id": "lung-M_N_RUA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Normal",
    "translatedType": "Normal (murmúrio vesicular)",
    "location": "RUA",
    "locationLabel": "Terço superior direito (anterior)",
    "csvId": "M_N_RUA",
    "audioFile": "M_N_RUA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_N_RUA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_N_LUA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Normal",
    "translatedType": "Normal (murmúrio vesicular)",
    "location": "LUA",
    "locationLabel": "Terço superior esquerdo (anterior)",
    "csvId": "F_N_LUA",
    "audioFile": "F_N_LUA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_N_LUA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_N_RMA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Normal",
    "translatedType": "Normal (murmúrio vesicular)",
    "location": "RMA",
    "locationLabel": "Terço médio direito (anterior)",
    "csvId": "F_N_RMA",
    "audioFile": "F_N_RMA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_N_RMA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_N_LMA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Normal",
    "translatedType": "Normal (murmúrio vesicular)",
    "location": "LMA",
    "locationLabel": "Terço médio esquerdo (anterior)",
    "csvId": "F_N_LMA",
    "audioFile": "F_N_LMA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_N_LMA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_N_RLA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Normal",
    "translatedType": "Normal (murmúrio vesicular)",
    "location": "RLA",
    "locationLabel": "Terço inferior direito (anterior)",
    "csvId": "M_N_RLA",
    "audioFile": "M_N_RLA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_N_RLA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_N_LLA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Normal",
    "translatedType": "Normal (murmúrio vesicular)",
    "location": "LLA",
    "locationLabel": "Terço inferior esquerdo (anterior)",
    "csvId": "M_N_LLA",
    "audioFile": "M_N_LLA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_N_LLA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_PR_RMA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Pleural Rub",
    "translatedType": "Atrito pleural",
    "location": "RMA",
    "locationLabel": "Terço médio direito (anterior)",
    "csvId": "M_PR_RMA",
    "audioFile": "M_PR_RMA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_PR_RMA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_PR_LUA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Pleural Rub",
    "translatedType": "Atrito pleural",
    "location": "LUA",
    "locationLabel": "Terço superior esquerdo (anterior)",
    "csvId": "M_PR_LUA",
    "audioFile": "M_PR_LUA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_PR_LUA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_R_LUA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Rhonchi",
    "translatedType": "Roncos",
    "location": "LUA",
    "locationLabel": "Terço superior esquerdo (anterior)",
    "csvId": "F_R_LUA",
    "audioFile": "F_R_LUA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_R_LUA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_W_LUA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Wheezing",
    "translatedType": "Sibilos",
    "location": "LUA",
    "locationLabel": "Terço superior esquerdo (anterior)",
    "csvId": "M_W_LUA",
    "audioFile": "M_W_LUA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_W_LUA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_C_LUA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Fine Crackles",
    "translatedType": "Crepitações finas",
    "location": "LUA",
    "locationLabel": "Terço superior esquerdo (anterior)",
    "csvId": "M_C_LUA",
    "audioFile": "M_FC_LUA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_FC_LUA.wav",
    "mappingType": "translated-code",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_N_LUA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Normal",
    "translatedType": "Normal (murmúrio vesicular)",
    "location": "LUA",
    "locationLabel": "Terço superior esquerdo (anterior)",
    "csvId": "M_N_LUA",
    "audioFile": "M_N_LUA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_N_LUA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_G_LLA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Coarse Crackles",
    "translatedType": "Crepitações grossas",
    "location": "LLA",
    "locationLabel": "Terço inferior esquerdo (anterior)",
    "csvId": "M_G_LLA",
    "audioFile": "M_CC_LLA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_CC_LLA.wav",
    "mappingType": "translated-code",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_G_LUA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Coarse Crackles",
    "translatedType": "Crepitações grossas",
    "location": "LUA",
    "locationLabel": "Terço superior esquerdo (anterior)",
    "csvId": "M_G_LUA",
    "audioFile": "M_CC_LUA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_CC_LUA.wav",
    "mappingType": "translated-code",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_C_LUA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Fine Crackles",
    "translatedType": "Crepitações finas",
    "location": "LUA",
    "locationLabel": "Terço superior esquerdo (anterior)",
    "csvId": "F_C_LUA",
    "audioFile": "F_FC_LUA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_FC_LUA.wav",
    "mappingType": "translated-code",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_G_RLA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Coarse Crackles",
    "translatedType": "Crepitações grossas",
    "location": "RLA",
    "locationLabel": "Terço inferior direito (anterior)",
    "csvId": "M_G_RLA",
    "audioFile": "M_CC_RLA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_CC_RLA.wav",
    "mappingType": "translated-code",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_R_RLA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Rhonchi",
    "translatedType": "Roncos",
    "location": "RLA",
    "locationLabel": "Terço inferior direito (anterior)",
    "csvId": "F_R_RLA",
    "audioFile": "F_R_RLA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_R_RLA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_W_RUA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Wheezing",
    "translatedType": "Sibilos",
    "location": "RUA",
    "locationLabel": "Terço superior direito (anterior)",
    "csvId": "F_W_RUA",
    "audioFile": "F_W_RUA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_W_RUA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_PR_LLA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Pleural Rub",
    "translatedType": "Atrito pleural",
    "location": "LLA",
    "locationLabel": "Terço inferior esquerdo (anterior)",
    "csvId": "M_PR_LLA",
    "audioFile": "M_PR_LLA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_PR_LLA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_PR_LMA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Pleural Rub",
    "translatedType": "Atrito pleural",
    "location": "LMA",
    "locationLabel": "Terço médio esquerdo (anterior)",
    "csvId": "M_PR_LMA",
    "audioFile": "M_PR_LMA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_PR_LMA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_R_RUA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Rhonchi",
    "translatedType": "Roncos",
    "location": "RUA",
    "locationLabel": "Terço superior direito (anterior)",
    "csvId": "M_R_RUA",
    "audioFile": "M_R_RUA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_R_RUA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_C_RUA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Fine Crackles",
    "translatedType": "Crepitações finas",
    "location": "RUA",
    "locationLabel": "Terço superior direito (anterior)",
    "csvId": "M_C_RUA",
    "audioFile": "M_FC_RUA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_FC_RUA.wav",
    "mappingType": "translated-code",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_R_LUA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Rhonchi",
    "translatedType": "Roncos",
    "location": "LUA",
    "locationLabel": "Terço superior esquerdo (anterior)",
    "csvId": "M_R_LUA",
    "audioFile": "M_R_LUA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_R_LUA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_PR_LMA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Pleural Rub",
    "translatedType": "Atrito pleural",
    "location": "LMA",
    "locationLabel": "Terço médio esquerdo (anterior)",
    "csvId": "F_PR_LMA",
    "audioFile": "F_PR_LMA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_PR_LMA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_G_LMA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Coarse Crackles",
    "translatedType": "Crepitações grossas",
    "location": "LMA",
    "locationLabel": "Terço médio esquerdo (anterior)",
    "csvId": "F_G_LMA",
    "audioFile": "F_CC_LMA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_CC_LMA.wav",
    "mappingType": "translated-code",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_G_RLA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Coarse Crackles",
    "translatedType": "Crepitações grossas",
    "location": "RLA",
    "locationLabel": "Terço inferior direito (anterior)",
    "csvId": "F_G_RLA",
    "audioFile": "F_CC_RLA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_CC_RLA.wav",
    "mappingType": "translated-code",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_C_RLA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Fine Crackles",
    "translatedType": "Crepitações finas",
    "location": "RLA",
    "locationLabel": "Terço inferior direito (anterior)",
    "csvId": "M_C_RLA",
    "audioFile": "M_FC_RLA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_FC_RLA.wav",
    "mappingType": "translated-code",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_G_RMA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Coarse Crackles",
    "translatedType": "Crepitações grossas",
    "location": "RMA",
    "locationLabel": "Terço médio direito (anterior)",
    "csvId": "F_G_RMA",
    "audioFile": "F_CC_RMA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_CC_RMA.wav",
    "mappingType": "translated-code",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_W_RLA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Wheezing",
    "translatedType": "Sibilos",
    "location": "RLA",
    "locationLabel": "Terço inferior direito (anterior)",
    "csvId": "M_W_RLA",
    "audioFile": "M_W_RLA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_W_RLA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_R_RLA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Rhonchi",
    "translatedType": "Roncos",
    "location": "RLA",
    "locationLabel": "Terço inferior direito (anterior)",
    "csvId": "M_R_RLA",
    "audioFile": "M_R_RLA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_R_RLA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_C_RLA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Fine Crackles",
    "translatedType": "Crepitações finas",
    "location": "RLA",
    "locationLabel": "Terço inferior direito (anterior)",
    "csvId": "F_C_RLA",
    "audioFile": "F_FC_RLA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_FC_RLA.wav",
    "mappingType": "translated-code",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_N_RMA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Normal",
    "translatedType": "Normal (murmúrio vesicular)",
    "location": "RMA",
    "locationLabel": "Terço médio direito (anterior)",
    "csvId": "M_N_RMA",
    "audioFile": "M_N_RMA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_N_RMA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_R_LMA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Rhonchi",
    "translatedType": "Roncos",
    "location": "LMA",
    "locationLabel": "Terço médio esquerdo (anterior)",
    "csvId": "M_R_LMA",
    "audioFile": "M_R_LMA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_R_LMA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_G_LLA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Coarse Crackles",
    "translatedType": "Crepitações grossas",
    "location": "LLA",
    "locationLabel": "Terço inferior esquerdo (anterior)",
    "csvId": "F_G_LLA",
    "audioFile": "F_CC_LLA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_CC_LLA.wav",
    "mappingType": "translated-code",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_R_LMA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Rhonchi",
    "translatedType": "Roncos",
    "location": "LMA",
    "locationLabel": "Terço médio esquerdo (anterior)",
    "csvId": "F_R_LMA",
    "audioFile": "F_R_LMA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_R_LMA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_N_LLA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Normal",
    "translatedType": "Normal (murmúrio vesicular)",
    "location": "LLA",
    "locationLabel": "Terço inferior esquerdo (anterior)",
    "csvId": "F_N_LLA",
    "audioFile": "F_N_LLA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_N_LLA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_W_RUA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Wheezing",
    "translatedType": "Sibilos",
    "location": "RUA",
    "locationLabel": "Terço superior direito (anterior)",
    "csvId": "M_W_RUA",
    "audioFile": "M_W_RUA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_W_RUA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_N_LMA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Normal",
    "translatedType": "Normal (murmúrio vesicular)",
    "location": "LMA",
    "locationLabel": "Terço médio esquerdo (anterior)",
    "csvId": "M_N_LMA",
    "audioFile": "M_N_LMA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_N_LMA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_PR_LLA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Pleural Rub",
    "translatedType": "Atrito pleural",
    "location": "LLA",
    "locationLabel": "Terço inferior esquerdo (anterior)",
    "csvId": "F_PR_LLA",
    "audioFile": "F_PR_LLA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_PR_LLA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_W_RMA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Wheezing",
    "translatedType": "Sibilos",
    "location": "RMA",
    "locationLabel": "Terço médio direito (anterior)",
    "csvId": "M_W_RMA",
    "audioFile": "M_W_RMA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_W_RMA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_PR_RUA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Pleural Rub",
    "translatedType": "Atrito pleural",
    "location": "RUA",
    "locationLabel": "Terço superior direito (anterior)",
    "csvId": "M_PR_RUA",
    "audioFile": "M_PR_RUA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_PR_RUA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_W_LLA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Wheezing",
    "translatedType": "Sibilos",
    "location": "LLA",
    "locationLabel": "Terço inferior esquerdo (anterior)",
    "csvId": "M_W_LLA",
    "audioFile": "M_W_LLA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_W_LLA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_R_LLA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Rhonchi",
    "translatedType": "Roncos",
    "location": "LLA",
    "locationLabel": "Terço inferior esquerdo (anterior)",
    "csvId": "M_R_LLA",
    "audioFile": "M_R_LLA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_R_LLA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_N_RLA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Normal",
    "translatedType": "Normal (murmúrio vesicular)",
    "location": "RLA",
    "locationLabel": "Terço inferior direito (anterior)",
    "csvId": "F_N_RLA",
    "audioFile": "F_N_RLA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_N_RLA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_G_LMA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Coarse Crackles",
    "translatedType": "Crepitações grossas",
    "location": "LMA",
    "locationLabel": "Terço médio esquerdo (anterior)",
    "csvId": "M_G_LMA",
    "audioFile": "M_CC_LMA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_CC_LMA.wav",
    "mappingType": "translated-code",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_W_LMA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Wheezing",
    "translatedType": "Sibilos",
    "location": "LMA",
    "locationLabel": "Terço médio esquerdo (anterior)",
    "csvId": "M_W_LMA",
    "audioFile": "M_W_LMA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_W_LMA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_N_RUA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Normal",
    "translatedType": "Normal (murmúrio vesicular)",
    "location": "RUA",
    "locationLabel": "Terço superior direito (anterior)",
    "csvId": "F_N_RUA",
    "audioFile": "F_N_RUA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_N_RUA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-M_PR_RLA",
    "category": "lung",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Pleural Rub",
    "translatedType": "Atrito pleural",
    "location": "RLA",
    "locationLabel": "Terço inferior direito (anterior)",
    "csvId": "M_PR_RLA",
    "audioFile": "M_PR_RLA.wav",
    "audioUrl": "/HLS-CMDS/LS/M_PR_RLA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_G_LUA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Coarse Crackles",
    "translatedType": "Crepitações grossas",
    "location": "LUA",
    "locationLabel": "Terço superior esquerdo (anterior)",
    "csvId": "F_G_LUA",
    "audioFile": "F_CC_LUA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_CC_LUA.wav",
    "mappingType": "translated-code",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "lung-F_PR_LUA",
    "category": "lung",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Pleural Rub",
    "translatedType": "Atrito pleural",
    "location": "LUA",
    "locationLabel": "Terço superior esquerdo (anterior)",
    "csvId": "F_PR_LUA",
    "audioFile": "F_PR_LUA.wav",
    "audioUrl": "/HLS-CMDS/LS/F_PR_LUA.wav",
    "mappingType": "exact",
    "sourceCsv": "LS.csv"
  },
  {
    "id": "heart-F_N_RC",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Normal",
    "translatedType": "Normal (B1 e B2)",
    "location": "RC",
    "locationLabel": "Carótida direita",
    "csvId": "F_N_RC",
    "audioFile": "F_N_RC.wav",
    "audioUrl": "/HLS-CMDS/HS/F_N_RC.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_N_LC",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Normal",
    "translatedType": "Normal (B1 e B2)",
    "location": "LC",
    "locationLabel": "Carótida esquerda",
    "csvId": "F_N_LC",
    "audioFile": "F_N_LC.wav",
    "audioUrl": "/HLS-CMDS/HS/F_N_LC.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_N_RUSB",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Normal",
    "translatedType": "Normal (B1 e B2)",
    "location": "RUSB",
    "locationLabel": "Foco aórtico (BED superior)",
    "csvId": "M_N_RUSB",
    "audioFile": "M_N_RUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/M_N_RUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_N_LUSB",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Normal",
    "translatedType": "Normal (B1 e B2)",
    "location": "LUSB",
    "locationLabel": "Foco pulmonar (BEE superior)",
    "csvId": "F_N_LUSB",
    "audioFile": "F_N_LUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/F_N_LUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_N_LLSB",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Normal",
    "translatedType": "Normal (B1 e B2)",
    "location": "LLSB",
    "locationLabel": "Foco tricúspide (BEE inferior)",
    "csvId": "F_N_LLSB",
    "audioFile": "F_N_LLSB.wav",
    "audioUrl": "/HLS-CMDS/HS/F_N_LLSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_N_A",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Normal",
    "translatedType": "Normal (B1 e B2)",
    "location": "Apex",
    "locationLabel": "Foco mitral (ápice)",
    "csvId": "F_N_A",
    "audioFile": "F_N_A.wav",
    "audioUrl": "/HLS-CMDS/HS/F_N_A.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_LDM_LC",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Late Diastolic Murmur",
    "translatedType": "Sopro diastólico tardio",
    "location": "LC",
    "locationLabel": "Carótida esquerda",
    "csvId": "M_LDM_LC",
    "audioFile": "M_LDM_LC.wav",
    "audioUrl": "/HLS-CMDS/HS/M_LDM_LC.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_MSM_A",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Mid Systolic Murmur",
    "translatedType": "Sopro mesossistólico",
    "location": "Apex",
    "locationLabel": "Foco mitral (ápice)",
    "csvId": "M_MSM_A",
    "audioFile": "M_MSM_A.wav",
    "audioUrl": "/HLS-CMDS/HS/M_MSM_A.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_N_RUSB",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Normal",
    "translatedType": "Normal (B1 e B2)",
    "location": "RUSB",
    "locationLabel": "Foco aórtico (BED superior)",
    "csvId": "F_N_RUSB",
    "audioFile": "F_N_RUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/F_N_RUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_MSM_A",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Mid Systolic Murmur",
    "translatedType": "Sopro mesossistólico",
    "location": "Apex",
    "locationLabel": "Foco mitral (ápice)",
    "csvId": "F_MSM_A",
    "audioFile": "F_MSM_A.wav",
    "audioUrl": "/HLS-CMDS/HS/F_MSM_A.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_N_LC",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Normal",
    "translatedType": "Normal (B1 e B2)",
    "location": "LC",
    "locationLabel": "Carótida esquerda",
    "csvId": "M_N_LC",
    "audioFile": "M_N_LC.wav",
    "audioUrl": "/HLS-CMDS/HS/M_N_LC.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_LSM_LUSB",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Late Systolic Murmur",
    "translatedType": "Sopro sistólico tardio",
    "location": "LUSB",
    "locationLabel": "Foco pulmonar (BEE superior)",
    "csvId": "F_LSM_LUSB",
    "audioFile": "F_LSM_LUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/F_LSM_LUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_LSM_RUSB",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Late Systolic Murmur",
    "translatedType": "Sopro sistólico tardio",
    "location": "RUSB",
    "locationLabel": "Foco aórtico (BED superior)",
    "csvId": "M_LSM_RUSB",
    "audioFile": "M_LSM_RUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/M_LSM_RUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_AF_A",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Atrial Fibrillation",
    "translatedType": "Fibrilação atrial",
    "location": "Apex",
    "locationLabel": "Foco mitral (ápice)",
    "csvId": "F_AF_A",
    "audioFile": "F_AF_A.wav",
    "audioUrl": "/HLS-CMDS/HS/F_AF_A.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_S4_RC",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "S4",
    "translatedType": "B4 (quarta bulha)",
    "location": "RC",
    "locationLabel": "Carótida direita",
    "csvId": "F_S4_RC",
    "audioFile": "F_S4_RC.wav",
    "audioUrl": "/HLS-CMDS/HS/F_S4_RC.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_ESM_RUSB",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Early Systolic Murmur",
    "translatedType": "Sopro protossistólico",
    "location": "RUSB",
    "locationLabel": "Foco aórtico (BED superior)",
    "csvId": "F_ESM_RUSB",
    "audioFile": "F_ESM_RUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/F_ESM_RUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_LSM_A",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Late Systolic Murmur",
    "translatedType": "Sopro sistólico tardio",
    "location": "Apex",
    "locationLabel": "Foco mitral (ápice)",
    "csvId": "F_LSM_A",
    "audioFile": "F_LSM_A.wav",
    "audioUrl": "/HLS-CMDS/HS/F_LSM_A.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_MSM_LUSB",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Mid Systolic Murmur",
    "translatedType": "Sopro mesossistólico",
    "location": "LUSB",
    "locationLabel": "Foco pulmonar (BEE superior)",
    "csvId": "M_MSM_LUSB",
    "audioFile": "M_MSM_LUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/M_MSM_LUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_ESM_LUSB",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Early Systolic Murmur",
    "translatedType": "Sopro protossistólico",
    "location": "LUSB",
    "locationLabel": "Foco pulmonar (BEE superior)",
    "csvId": "F_ESM_LUSB",
    "audioFile": "F_ESM_LUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/F_ESM_LUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_MSM_RC",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Mid Systolic Murmur",
    "translatedType": "Sopro mesossistólico",
    "location": "RC",
    "locationLabel": "Carótida direita",
    "csvId": "M_MSM_RC",
    "audioFile": "M_MSM_RC.wav",
    "audioUrl": "/HLS-CMDS/HS/M_MSM_RC.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_LDM_LUSB",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Late Diastolic Murmur",
    "translatedType": "Sopro diastólico tardio",
    "location": "LUSB",
    "locationLabel": "Foco pulmonar (BEE superior)",
    "csvId": "M_LDM_LUSB",
    "audioFile": "M_LDM_LUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/M_LDM_LUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_ESM_RUSB",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Early Systolic Murmur",
    "translatedType": "Sopro protossistólico",
    "location": "RUSB",
    "locationLabel": "Foco aórtico (BED superior)",
    "csvId": "M_ESM_RUSB",
    "audioFile": "M_ESM_RUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/M_ESM_RUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_S3_LUSB",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "S3",
    "translatedType": "B3 (terceira bulha)",
    "location": "LUSB",
    "locationLabel": "Foco pulmonar (BEE superior)",
    "csvId": "M_S3_LUSB",
    "audioFile": "M_S3_LUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/M_S3_LUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_LDM_A",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Late Diastolic Murmur",
    "translatedType": "Sopro diastólico tardio",
    "location": "Apex",
    "locationLabel": "Foco mitral (ápice)",
    "csvId": "F_LDM_A",
    "audioFile": "F_LDM_A.wav",
    "audioUrl": "/HLS-CMDS/HS/F_LDM_A.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_ESM_LUSB",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Early Systolic Murmur",
    "translatedType": "Sopro protossistólico",
    "location": "LUSB",
    "locationLabel": "Foco pulmonar (BEE superior)",
    "csvId": "M_ESM_LUSB",
    "audioFile": "M_ESM_LUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/M_ESM_LUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_S3_LLSB",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "S3",
    "translatedType": "B3 (terceira bulha)",
    "location": "LLSB",
    "locationLabel": "Foco tricúspide (BEE inferior)",
    "csvId": "F_S3_LLSB",
    "audioFile": "F_S3_LLSB.wav",
    "audioUrl": "/HLS-CMDS/HS/F_S3_LLSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_LDM_LLSB",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Late Diastolic Murmur",
    "translatedType": "Sopro diastólico tardio",
    "location": "LLSB",
    "locationLabel": "Foco tricúspide (BEE inferior)",
    "csvId": "M_LDM_LLSB",
    "audioFile": "M_LDM_LLSB.wav",
    "audioUrl": "/HLS-CMDS/HS/M_LDM_LLSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_AF_LUSB",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Atrial Fibrillation",
    "translatedType": "Fibrilação atrial",
    "location": "LUSB",
    "locationLabel": "Foco pulmonar (BEE superior)",
    "csvId": "F_AF_LUSB",
    "audioFile": "F_AF_LUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/F_AF_LUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_T_RC",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Tachycardia",
    "translatedType": "Taquicardia",
    "location": "LC",
    "locationLabel": "Carótida esquerda",
    "csvId": "F_T_RC",
    "audioFile": "F_T_RC.wav",
    "audioUrl": "/HLS-CMDS/HS/F_T_RC.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_T_A",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Tachycardia",
    "translatedType": "Taquicardia",
    "location": "Apex",
    "locationLabel": "Foco mitral (ápice)",
    "csvId": "F_T_A",
    "audioFile": "F_T_A.wav",
    "audioUrl": "/HLS-CMDS/HS/F_T_A.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_LDM_LUSB",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Late Diastolic Murmur",
    "translatedType": "Sopro diastólico tardio",
    "location": "LUSB",
    "locationLabel": "Foco pulmonar (BEE superior)",
    "csvId": "F_LDM_LUSB",
    "audioFile": "F_LDM_LUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/F_LDM_LUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_S3_A",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "S3",
    "translatedType": "B3 (terceira bulha)",
    "location": "Apex",
    "locationLabel": "Foco mitral (ápice)",
    "csvId": "F_S3_A",
    "audioFile": "F_S3_A.wav",
    "audioUrl": "/HLS-CMDS/HS/F_S3_A.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_S4_LUSB",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "S4",
    "translatedType": "B4 (quarta bulha)",
    "location": "LUSB",
    "locationLabel": "Foco pulmonar (BEE superior)",
    "csvId": "M_S4_LUSB",
    "audioFile": "M_S4_LUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/M_S4_LUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_AVB_LLSB",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "AV Block",
    "translatedType": "Bloqueio AV",
    "location": "LLSB",
    "locationLabel": "Foco tricúspide (BEE inferior)",
    "csvId": "M_AVB_LLSB",
    "audioFile": "M_AVB_LLSB.wav",
    "audioUrl": "/HLS-CMDS/HS/M_AVB_LLSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_S3_LC",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "S3",
    "translatedType": "B3 (terceira bulha)",
    "location": "LC",
    "locationLabel": "Carótida esquerda",
    "csvId": "F_S3_LC",
    "audioFile": "F_S3_LC.wav",
    "audioUrl": "/HLS-CMDS/HS/F_S3_LC.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_AVB_A",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "AV Block",
    "translatedType": "Bloqueio AV",
    "location": "Apex",
    "locationLabel": "Foco mitral (ápice)",
    "csvId": "M_AVB_A",
    "audioFile": "M_AVB_A.wav",
    "audioUrl": "/HLS-CMDS/HS/M_AVB_A.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_T_LUSB",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Tachycardia",
    "translatedType": "Taquicardia",
    "location": "LUSB",
    "locationLabel": "Foco pulmonar (BEE superior)",
    "csvId": "M_T_LUSB",
    "audioFile": "M_T_LUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/M_T_LUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_AF_LC",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Atrial Fibrillation",
    "translatedType": "Fibrilação atrial",
    "location": "LC",
    "locationLabel": "Carótida esquerda",
    "csvId": "M_AF_LC",
    "audioFile": "M_AF_LC.wav",
    "audioUrl": "/HLS-CMDS/HS/M_AF_LC.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_LSM_LUSB",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Late Systolic Murmur",
    "translatedType": "Sopro sistólico tardio",
    "location": "LUSB",
    "locationLabel": "Foco pulmonar (BEE superior)",
    "csvId": "M_LSM_LUSB",
    "audioFile": "M_LSM_LUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/M_LSM_LUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_LDM_LLSB",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Late Diastolic Murmur",
    "translatedType": "Sopro diastólico tardio",
    "location": "LLSB",
    "locationLabel": "Foco tricúspide (BEE inferior)",
    "csvId": "F_LDM_LLSB",
    "audioFile": "F_LDM_LLSB.wav",
    "audioUrl": "/HLS-CMDS/HS/F_LDM_LLSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_MSM_LUSB",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Mid Systolic Murmur",
    "translatedType": "Sopro mesossistólico",
    "location": "LUSB",
    "locationLabel": "Foco pulmonar (BEE superior)",
    "csvId": "F_MSM_LUSB",
    "audioFile": "F_MSM_LUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/F_MSM_LUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_MSM_LLSB",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Mid Systolic Murmur",
    "translatedType": "Sopro mesossistólico",
    "location": "LLSB",
    "locationLabel": "Foco tricúspide (BEE inferior)",
    "csvId": "F_MSM_LLSB",
    "audioFile": "F_MSM_LLSB.wav",
    "audioUrl": "/HLS-CMDS/HS/F_MSM_LLSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_AVB_RC",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "AV Block",
    "translatedType": "Bloqueio AV",
    "location": "RC",
    "locationLabel": "Carótida direita",
    "csvId": "M_AVB_RC",
    "audioFile": "M_AVB_RC.wav",
    "audioUrl": "/HLS-CMDS/HS/M_AVB_RC.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_N_LLSB",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Normal",
    "translatedType": "Normal (B1 e B2)",
    "location": "LLSB",
    "locationLabel": "Foco tricúspide (BEE inferior)",
    "csvId": "M_N_LLSB",
    "audioFile": "M_N_LLSB.wav",
    "audioUrl": "/HLS-CMDS/HS/M_N_LLSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_MSM_RUSB",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Mid Systolic Murmur",
    "translatedType": "Sopro mesossistólico",
    "location": "RUSB",
    "locationLabel": "Foco aórtico (BED superior)",
    "csvId": "M_MSM_RUSB",
    "audioFile": "M_MSM_RUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/M_MSM_RUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_S3_LLSB",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "S3",
    "translatedType": "B3 (terceira bulha)",
    "location": "LLSB",
    "locationLabel": "Foco tricúspide (BEE inferior)",
    "csvId": "M_S3_LLSB",
    "audioFile": "M_S3_LLSB.wav",
    "audioUrl": "/HLS-CMDS/HS/M_S3_LLSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_ESM_LLSB",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Early Systolic Murmur",
    "translatedType": "Sopro protossistólico",
    "location": "LLSB",
    "locationLabel": "Foco tricúspide (BEE inferior)",
    "csvId": "F_ESM_LLSB",
    "audioFile": "F_ESM_LLSB.wav",
    "audioUrl": "/HLS-CMDS/HS/F_ESM_LLSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-F_LSM_LLSB",
    "category": "heart",
    "gender": "F",
    "genderLabel": "Feminino",
    "originalType": "Late Systolic Murmur",
    "translatedType": "Sopro sistólico tardio",
    "location": "LLSB",
    "locationLabel": "Foco tricúspide (BEE inferior)",
    "csvId": "F_LSM_LLSB",
    "audioFile": "F_LSM_LLSB.wav",
    "audioUrl": "/HLS-CMDS/HS/F_LSM_LLSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_ESM_A",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Early Systolic Murmur",
    "translatedType": "Sopro protossistólico",
    "location": "Apex",
    "locationLabel": "Foco mitral (ápice)",
    "csvId": "M_ESM_A",
    "audioFile": "M_ESM_A.wav",
    "audioUrl": "/HLS-CMDS/HS/M_ESM_A.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  },
  {
    "id": "heart-M_AF_RUSB",
    "category": "heart",
    "gender": "M",
    "genderLabel": "Masculino",
    "originalType": "Atrial Fibrillation",
    "translatedType": "Fibrilação atrial",
    "location": "RUSB",
    "locationLabel": "Foco aórtico (BED superior)",
    "csvId": "M_AF_RUSB",
    "audioFile": "M_AF_RUSB.wav",
    "audioUrl": "/HLS-CMDS/HS/M_AF_RUSB.wav",
    "mappingType": "exact",
    "sourceCsv": "HS.csv"
  }
];

export const LUNG_SOUNDS = CLINICAL_SOUNDS.filter((s) => s.category === "lung");
export const HEART_SOUNDS = CLINICAL_SOUNDS.filter((s) => s.category === "heart");
