// Banco de mídias interativas do Exame Físico Pediátrico
// Mapeamento de ação → imagem ou guia textual
// Estrutura definitiva com 44 imagens previstas

export type TipoMidiaExamePediatrico = "imagem" | "guia" | "audio" | "interativo";

export interface MidiaExamePediatrico {
  regiaoId: string;
  acaoId: string;
  titulo: string;
  descricao: string;
  tipo: TipoMidiaExamePediatrico;
  src?: string;
  legenda?: string;
  arquivoSugerido?: string;
  prioridade?: "alta" | "media" | "baixa";
}

const MIDIAS_EXAME_PEDIATRICO: Record<string, MidiaExamePediatrico> = {
  // =========================================================================
  // 1. ESTADO GERAL - APENAS GUIA TEXTUAL
  // =========================================================================
  "estado_geral:avaliar_estado_geral": {
    regiaoId: "estado_geral",
    acaoId: "avaliar_estado_geral",
    titulo: "Estado geral da criança",
    descricao: "Observe aparência geral, responsividade, atividade espontânea, interação com o responsável, hidratação aparente, padrão respiratório e sinais de gravidade.",
    tipo: "guia",
    prioridade: "alta",
  },
  "estado_geral:avaliar_nivel_atividade": {
    regiaoId: "estado_geral",
    acaoId: "avaliar_nivel_atividade",
    titulo: "Estado geral da criança",
    descricao: "Observe aparência geral, responsividade, atividade espontânea, interação com o responsável, hidratação aparente, padrão respiratório e sinais de gravidade.",
    tipo: "guia",
    prioridade: "media",
  },
  "estado_geral:avaliar_consciencia_responsividade": {
    regiaoId: "estado_geral",
    acaoId: "avaliar_consciencia_responsividade",
    titulo: "Estado geral da criança",
    descricao: "Observe aparência geral, responsividade, atividade espontânea, interação com o responsável, hidratação aparente, padrão respiratório e sinais de gravidade.",
    tipo: "guia",
    prioridade: "media",
  },
  "estado_geral:avaliar_sinais_gravidade": {
    regiaoId: "estado_geral",
    acaoId: "avaliar_sinais_gravidade",
    titulo: "Estado geral da criança",
    descricao: "Observe aparência geral, responsividade, atividade espontânea, interação com o responsável, hidratação aparente, padrão respiratório e sinais de gravidade.",
    tipo: "guia",
    prioridade: "alta",
  },
  "estado_geral:avaliar_interacao_com_responsavel": {
    regiaoId: "estado_geral",
    acaoId: "avaliar_interacao_com_responsavel",
    titulo: "Estado geral da criança",
    descricao: "Observe aparência geral, responsividade, atividade espontânea, interação com o responsável, hidratação aparente, padrão respiratório e sinais de gravidade.",
    tipo: "guia",
    prioridade: "media",
  },

  // =========================================================================
  // 2. ANTROPOMETRIA E CRESCIMENTO - UMA IMAGEM CONDENSADA
  // =========================================================================
  "antropometria_crescimento:medir_peso": {
    regiaoId: "antropometria_crescimento",
    acaoId: "medir_peso",
    titulo: "Antropometria pediátrica",
    descricao: "Imagem condensada com peso, comprimento/estatura, perímetro cefálico, circunferência braquial e avaliação em curvas de crescimento.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/antropometria-crescimento/antropometria-pediatrica.png",
    arquivoSugerido: "antropometria-pediatrica.png",
    prioridade: "alta",
  },
  "antropometria_crescimento:medir_estatura_ou_comprimento": {
    regiaoId: "antropometria_crescimento",
    acaoId: "medir_estatura_ou_comprimento",
    titulo: "Antropometria pediátrica",
    descricao: "Imagem condensada com peso, comprimento/estatura, perímetro cefálico, circunferência braquial e avaliação em curvas de crescimento.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/antropometria-crescimento/antropometria-pediatrica.png",
    arquivoSugerido: "antropometria-pediatrica.png",
    prioridade: "alta",
  },
  "antropometria_crescimento:medir_perimetro_cefalico": {
    regiaoId: "antropometria_crescimento",
    acaoId: "medir_perimetro_cefalico",
    titulo: "Antropometria pediátrica",
    descricao: "Imagem condensada com peso, comprimento/estatura, perímetro cefálico, circunferência braquial e avaliação em curvas de crescimento.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/antropometria-crescimento/antropometria-pediatrica.png",
    arquivoSugerido: "antropometria-pediatrica.png",
    prioridade: "alta",
  },
  "antropometria_crescimento:medir_circunferencia_braquial": {
    regiaoId: "antropometria_crescimento",
    acaoId: "medir_circunferencia_braquial",
    titulo: "Antropometria pediátrica",
    descricao: "Imagem condensada com peso, comprimento/estatura, perímetro cefálico, circunferência braquial e avaliação em curvas de crescimento.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/antropometria-crescimento/antropometria-pediatrica.png",
    arquivoSugerido: "antropometria-pediatrica.png",
    prioridade: "media",
  },
  "antropometria_crescimento:medir_circunferencia_abdominal": {
    regiaoId: "antropometria_crescimento",
    acaoId: "medir_circunferencia_abdominal",
    titulo: "Antropometria pediátrica",
    descricao: "Imagem condensada com peso, comprimento/estatura, perímetro cefálico, circunferência braquial e avaliação em curvas de crescimento.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/antropometria-crescimento/antropometria-pediatrica.png",
    arquivoSugerido: "antropometria-pediatrica.png",
    prioridade: "media",
  },
  "antropometria_crescimento:avaliar_curvas_crescimento": {
    regiaoId: "antropometria_crescimento",
    acaoId: "avaliar_curvas_crescimento",
    titulo: "Antropometria pediátrica",
    descricao: "Imagem condensada com peso, comprimento/estatura, perímetro cefálico, circunferência braquial e avaliação em curvas de crescimento.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/antropometria-crescimento/antropometria-pediatrica.png",
    arquivoSugerido: "antropometria-pediatrica.png",
    prioridade: "alta",
  },

  // =========================================================================
  // 3. CABEÇA E PERÍMETRO - APENAS GUIA TEXTUAL
  // =========================================================================
  "cabeca_perimetro:avaliar_formato_cranio": {
    regiaoId: "cabeca_perimetro",
    acaoId: "avaliar_formato_cranio",
    titulo: "Cabeça e perímetro cefálico",
    descricao: "Inspecione formato do crânio, fontanelas quando aplicável, suturas, assimetrias e técnica correta de medida do perímetro cefálico.",
    tipo: "guia",
    prioridade: "alta",
  },
  "cabeca_perimetro:avaliar_fontanela": {
    regiaoId: "cabeca_perimetro",
    acaoId: "avaliar_fontanela",
    titulo: "Cabeça e perímetro cefálico",
    descricao: "Inspecione formato do crânio, fontanelas quando aplicável, suturas, assimetrias e técnica correta de medida do perímetro cefálico.",
    tipo: "guia",
    prioridade: "alta",
  },
  "cabeca_perimetro:avaliar_suturas_cranianas": {
    regiaoId: "cabeca_perimetro",
    acaoId: "avaliar_suturas_cranianas",
    titulo: "Cabeça e perímetro cefálico",
    descricao: "Inspecione formato do crânio, fontanelas quando aplicável, suturas, assimetrias e técnica correta de medida do perímetro cefálico.",
    tipo: "guia",
    prioridade: "media",
  },
  "cabeca_perimetro:avaliar_sinais_trauma_cranio": {
    regiaoId: "cabeca_perimetro",
    acaoId: "avaliar_sinais_trauma_cranio",
    titulo: "Cabeça e perímetro cefálico",
    descricao: "Inspecione formato do crânio, fontanelas quando aplicável, suturas, assimetrias e técnica correta de medida do perímetro cefálico.",
    tipo: "guia",
    prioridade: "media",
  },

  // =========================================================================
  // 4. DESENVOLVIMENTO - APENAS GUIA TEXTUAL
  // =========================================================================
  "desenvolvimento:avaliar_marcos_motores": {
    regiaoId: "desenvolvimento",
    acaoId: "avaliar_marcos_motores",
    titulo: "Desenvolvimento neuropsicomotor",
    descricao: "Avalie marcos motores, linguagem, interação social, motricidade fina e compatibilidade dos achados com a faixa etária.",
    tipo: "guia",
    prioridade: "alta",
  },
  "desenvolvimento:avaliar_marcos_linguagem": {
    regiaoId: "desenvolvimento",
    acaoId: "avaliar_marcos_linguagem",
    titulo: "Desenvolvimento neuropsicomotor",
    descricao: "Avalie marcos motores, linguagem, interação social, motricidade fina e compatibilidade dos achados com a faixa etária.",
    tipo: "guia",
    prioridade: "alta",
  },
  "desenvolvimento:avaliar_marcos_sociais": {
    regiaoId: "desenvolvimento",
    acaoId: "avaliar_marcos_sociais",
    titulo: "Desenvolvimento neuropsicomotor",
    descricao: "Avalie marcos motores, linguagem, interação social, motricidade fina e compatibilidade dos achados com a faixa etária.",
    tipo: "guia",
    prioridade: "media",
  },
  "desenvolvimento:avaliar_motricidade_fina": {
    regiaoId: "desenvolvimento",
    acaoId: "avaliar_motricidade_fina",
    titulo: "Desenvolvimento neuropsicomotor",
    descricao: "Avalie marcos motores, linguagem, interação social, motricidade fina e compatibilidade dos achados com a faixa etária.",
    tipo: "guia",
    prioridade: "media",
  },
  "desenvolvimento:avaliar_interacao_social": {
    regiaoId: "desenvolvimento",
    acaoId: "avaliar_interacao_social",
    titulo: "Desenvolvimento neuropsicomotor",
    descricao: "Avalie marcos motores, linguagem, interação social, motricidade fina e compatibilidade dos achados com a faixa etária.",
    tipo: "guia",
    prioridade: "media",
  },
  "desenvolvimento:comparar_marcos_com_idade": {
    regiaoId: "desenvolvimento",
    acaoId: "comparar_marcos_com_idade",
    titulo: "Desenvolvimento neuropsicomotor",
    descricao: "Avalie marcos motores, linguagem, interação social, motricidade fina e compatibilidade dos achados com a faixa etária.",
    tipo: "guia",
    prioridade: "alta",
  },

  // =========================================================================
  // 5. FACE E OLHOS
  // =========================================================================
  "face_olhos:avaliar_palidez_conjuntival": {
    regiaoId: "face_olhos",
    acaoId: "avaliar_palidez_conjuntival",
    titulo: "Palidez conjuntival",
    descricao: "Comparativo entre conjuntiva normocorada e conjuntiva pálida.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/face-olhos/palidez-conjuntival-comparativo.png",
    arquivoSugerido: "palidez-conjuntival-comparativo.png",
    prioridade: "alta",
  },
  "face_olhos:avaliar_cianose_central": {
    regiaoId: "face_olhos",
    acaoId: "avaliar_cianose_central",
    titulo: "Cianose central",
    descricao: "Coloração azulada em lábios e mucosa oral.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/face-olhos/cianose-central.png",
    arquivoSugerido: "cianose-central.png",
    prioridade: "alta",
  },
  "face_olhos:avaliar_sinais_desidratacao": {
    regiaoId: "face_olhos",
    acaoId: "avaliar_sinais_desidratacao",
    titulo: "Sinais de desidratação",
    descricao: "Enofitalmia e presença de lágrimas.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/face-olhos/desidratacao-olhos.png",
    arquivoSugerido: "desidratacao-olhos.png",
    prioridade: "media",
  },
  "face_olhos:avaliar_conjuntivite": {
    regiaoId: "face_olhos",
    acaoId: "avaliar_conjuntivite",
    titulo: "Conjuntivite",
    descricao: "Hiperemia conjuntival e secreção.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/face-olhos/conjuntivite.png",
    arquivoSugerido: "conjuntivite.png",
    prioridade: "media",
  },
  "face_olhos:avaliar_face_toxemica": {
    regiaoId: "face_olhos",
    acaoId: "avaliar_face_toxemica",
    titulo: "Aparência geral da face",
    descricao: "Observe expressão facial e sinais de comprometimento sistêmico.",
    tipo: "guia",
    prioridade: "media",
  },

  // =========================================================================
  // 6. ORL E OROFARINGE
  // =========================================================================
  "orl_orofaringe:avaliar_orofaringe": {
    regiaoId: "orl_orofaringe",
    acaoId: "avaliar_orofaringe",
    titulo: "Orofaringe e amígdalas",
    descricao: "Observe color, eritema e tamanho.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/orl-orofaringe/orofaringe-amigdalas.png",
    arquivoSugerido: "orofaringe-amigdalas.png",
    prioridade: "alta",
  },
  "orl_orofaringe:avaliar_amigdalas": {
    regiaoId: "orl_orofaringe",
    acaoId: "avaliar_amigdalas",
    titulo: "Orofaringe e amígdalas",
    descricao: "Observe color, eritema e tamanho.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/orl-orofaringe/orofaringe-amigdalas.png",
    arquivoSugerido: "orofaringe-amigdalas.png",
    prioridade: "alta",
  },
  "orl_orofaringe:avaliar_mucosa_oral": {
    regiaoId: "orl_orofaringe",
    acaoId: "avaliar_mucosa_oral",
    titulo: "Orofaringe e amígdalas",
    descricao: "Observe color, eritema e tamanho.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/orl-orofaringe/orofaringe-amigdalas.png",
    arquivoSugerido: "orofaringe-amigdalas.png",
    prioridade: "alta",
  },
  "orl_orofaringe:avaliar_secrecao_nasal": {
    regiaoId: "orl_orofaringe",
    acaoId: "avaliar_secrecao_nasal",
    titulo: "Secreção nasal",
    descricao: "Observe tipo e congestão nasal.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/orl-orofaringe/secrecao-nasal.png",
    arquivoSugerido: "secrecao-nasal.png",
    prioridade: "media",
  },
  "orl_orofaringe:avaliar_congestao_nasal": {
    regiaoId: "orl_orofaringe",
    acaoId: "avaliar_congestao_nasal",
    titulo: "Secreção nasal",
    descricao: "Observe tipo e congestão nasal.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/orl-orofaringe/secrecao-nasal.png",
    arquivoSugerido: "secrecao-nasal.png",
    prioridade: "media",
  },
  "orl_orofaringe:avaliar_manchas_koplik": {
    regiaoId: "orl_orofaringe",
    acaoId: "avaliar_manchas_koplik",
    titulo: "Manchas de Koplik",
    descricao: "Manchas características de sarampo.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/orl-orofaringe/manchas-koplik.png",
    arquivoSugerido: "manchas-koplik.png",
    prioridade: "media",
  },
  "orl_orofaringe:avaliar_sinais_otite": {
    regiaoId: "orl_orofaringe",
    acaoId: "avaliar_sinais_otite",
    titulo: "Otoscopia",
    descricao: "Observe membrana timpânica para sinais de infecção.",
    tipo: "guia",
    prioridade: "media",
  },

  // =========================================================================
  // 7. PESCOÇO E LINFONODOS
  // =========================================================================
  "pescoco_linfonodos:palpar_linfonodos_cervicais": {
    regiaoId: "pescoco_linfonodos",
    acaoId: "palpar_linfonodos_cervicais",
    titulo: "Palpação de linfonodos cervicais",
    descricao: "Diagrama das cadeias linfonodais com localização.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pescoco-linfonodos/linfonodos-cabeca-pescoco.png",
    arquivoSugerido: "linfonodos-cabeca-pescoco.png",
    prioridade: "alta",
  },
  "pescoco_linfonodos:palpar_cadeia_submentoniana": {
    regiaoId: "pescoco_linfonodos",
    acaoId: "palpar_cadeia_submentoniana",
    titulo: "Palpação de linfonodos cervicais",
    descricao: "Diagrama das cadeias linfonodais com localização.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pescoco-linfonodos/linfonodos-cabeca-pescoco.png",
    arquivoSugerido: "linfonodos-cabeca-pescoco.png",
    prioridade: "alta",
  },
  "pescoco_linfonodos:palpar_cadeia_submandibular": {
    regiaoId: "pescoco_linfonodos",
    acaoId: "palpar_cadeia_submandibular",
    titulo: "Palpação de linfonodos cervicais",
    descricao: "Diagrama das cadeias linfonodais com localização.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pescoco-linfonodos/linfonodos-cabeca-pescoco.png",
    arquivoSugerido: "linfonodos-cabeca-pescoco.png",
    prioridade: "alta",
  },
  "pescoco_linfonodos:palpar_cervical_anterior": {
    regiaoId: "pescoco_linfonodos",
    acaoId: "palpar_cervical_anterior",
    titulo: "Palpação de linfonodos cervicais",
    descricao: "Diagrama das cadeias linfonodais com localização.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pescoco-linfonodos/linfonodos-cabeca-pescoco.png",
    arquivoSugerido: "linfonodos-cabeca-pescoco.png",
    prioridade: "alta",
  },
  "pescoco_linfonodos:palpar_cervical_posterior": {
    regiaoId: "pescoco_linfonodos",
    acaoId: "palpar_cervical_posterior",
    titulo: "Palpação de linfonodos cervicais",
    descricao: "Diagrama das cadeias linfonodais com localização.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pescoco-linfonodos/linfonodos-cabeca-pescoco.png",
    arquivoSugerido: "linfonodos-cabeca-pescoco.png",
    prioridade: "alta",
  },
  "pescoco_linfonodos:palpar_supraclaviculares": {
    regiaoId: "pescoco_linfonodos",
    acaoId: "palpar_supraclaviculares",
    titulo: "Palpação de linfonodos cervicais",
    descricao: "Diagrama das cadeias linfonodais com localização.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pescoco-linfonodos/linfonodos-cabeca-pescoco.png",
    arquivoSugerido: "linfonodos-cabeca-pescoco.png",
    prioridade: "alta",
  },
  "pescoco_linfonodos:palpar_occipitais": {
    regiaoId: "pescoco_linfonodos",
    acaoId: "palpar_occipitais",
    titulo: "Palpação de linfonodos cervicais",
    descricao: "Diagrama das cadeias linfonodais com localização.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pescoco-linfonodos/linfonodos-cabeca-pescoco.png",
    arquivoSugerido: "linfonodos-cabeca-pescoco.png",
    prioridade: "media",
  },
  "pescoco_linfonodos:descrever_linfonodos": {
    regiaoId: "pescoco_linfonodos",
    acaoId: "descrever_linfonodos",
    titulo: "Palpação de linfonodos cervicais",
    descricao: "Diagrama das cadeias linfonodais com localização.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pescoco-linfonodos/linfonodos-cabeca-pescoco.png",
    arquivoSugerido: "linfonodos-cabeca-pescoco.png",
    prioridade: "alta",
  },
  "pescoco_linfonodos:avaliar_rigidez_nuca": {
    regiaoId: "pescoco_linfonodos",
    acaoId: "avaliar_rigidez_nuca",
    titulo: "Rigidez de nuca",
    descricao: "Manobra de flexão para pesquisa de irritação meníngea.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pescoco-linfonodos/rigidez-nuca.png",
    arquivoSugerido: "rigidez-nuca.png",
    prioridade: "alta",
  },

  // =========================================================================
  // 8. TÓRAX RESPIRATÓRIO
  // =========================================================================
  "torax_respiratorio:avaliar_frequencia_respiratoria": {
    regiaoId: "torax_respiratorio",
    acaoId: "avaliar_frequencia_respiratoria",
    titulo: "Frequência respiratória",
    descricao: "Valores normais por faixa etária.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/torax-respiratorio/frequencia-respiratoria.png",
    arquivoSugerido: "frequencia-respiratoria.png",
    prioridade: "alta",
  },
  "torax_respiratorio:avaliar_padrao_respiratorio": {
    regiaoId: "torax_respiratorio",
    acaoId: "avaliar_padrao_respiratorio",
    titulo: "Padrão respiratório",
    descricao: "Avalie tipo de respiração e ritmo.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/torax-respiratorio/frequencia-respiratoria.png",
    arquivoSugerido: "frequencia-respiratoria.png",
    prioridade: "alta",
  },
  "torax_respiratorio:avaliar_tiragens": {
    regiaoId: "torax_respiratorio",
    acaoId: "avaliar_tiragens",
    titulo: "Sinais de esforço respiratório",
    descricao: "Observe tiragens em diferentes níveis.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/torax-respiratorio/tiragens.png",
    arquivoSugerido: "tiragens.png",
    prioridade: "alta",
  },
  "torax_respiratorio:avaliar_expansibilidade_toracica": {
    regiaoId: "torax_respiratorio",
    acaoId: "avaliar_expansibilidade_toracica",
    titulo: "Expansibilidade torácica",
    descricao: "Avalie simetria bilateral.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/torax-respiratorio/expansibilidade-toracica.png",
    arquivoSugerido: "expansibilidade-toracica.png",
    prioridade: "media",
  },
  "torax_respiratorio:avaliar_sinais_esforco_respiratorio": {
    regiaoId: "torax_respiratorio",
    acaoId: "avaliar_sinais_esforco_respiratorio",
    titulo: "Sinais de esforço respiratório",
    descricao: "Observe sinais de dificuldade respiratória.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/torax-respiratorio/tiragens.png",
    arquivoSugerido: "tiragens.png",
    prioridade: "alta",
  },
  "torax_respiratorio:auscultar_pulmoes_anterior": {
    regiaoId: "torax_respiratorio",
    acaoId: "auscultar_pulmoes_anterior",
    titulo: "Ausculta pulmonar anterior",
    descricao: "Posições de ausculta anterior.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/torax-respiratorio/ausculta-pulmonar-anterior.png",
    arquivoSugerido: "ausculta-pulmonar-anterior.png",
    prioridade: "alta",
  },
  "torax_respiratorio:auscultar_pulmoes_posterior": {
    regiaoId: "torax_respiratorio",
    acaoId: "auscultar_pulmoes_posterior",
    titulo: "Ausculta pulmonar posterior",
    descricao: "Posições de ausculta posterior.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/torax-respiratorio/ausculta-pulmonar-posterior.png",
    arquivoSugerido: "ausculta-pulmonar-posterior.png",
    prioridade: "alta",
  },
  "torax_respiratorio:avaliar_murmurio_vesicular": {
    regiaoId: "torax_respiratorio",
    acaoId: "avaliar_murmurio_vesicular",
    titulo: "Ausculta pulmonar anterior",
    descricao: "Posições de ausculta anterior.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/torax-respiratorio/ausculta-pulmonar-anterior.png",
    arquivoSugerido: "ausculta-pulmonar-anterior.png",
    prioridade: "alta",
  },
  "torax_respiratorio:avaliar_sibilos": {
    regiaoId: "torax_respiratorio",
    acaoId: "avaliar_sibilos",
    titulo: "Ausculta pulmonar anterior",
    descricao: "Posições de ausculta anterior.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/torax-respiratorio/ausculta-pulmonar-anterior.png",
    arquivoSugerido: "ausculta-pulmonar-anterior.png",
    prioridade: "alta",
  },
  "torax_respiratorio:avaliar_crepitacoes": {
    regiaoId: "torax_respiratorio",
    acaoId: "avaliar_crepitacoes",
    titulo: "Ausculta pulmonar anterior",
    descricao: "Posições de ausculta anterior.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/torax-respiratorio/ausculta-pulmonar-anterior.png",
    arquivoSugerido: "ausculta-pulmonar-anterior.png",
    prioridade: "alta",
  },
  "torax_respiratorio:avaliar_roncos": {
    regiaoId: "torax_respiratorio",
    acaoId: "avaliar_roncos",
    titulo: "Ausculta pulmonar anterior",
    descricao: "Posições de ausculta anterior.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/torax-respiratorio/ausculta-pulmonar-anterior.png",
    arquivoSugerido: "ausculta-pulmonar-anterior.png",
    prioridade: "media",
  },
  "torax_respiratorio:percutir_torax": {
    regiaoId: "torax_respiratorio",
    acaoId: "percutir_torax",
    titulo: "Percussão torácica",
    descricao: "Técnica de percussão para avaliação de sons.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/torax-respiratorio/percussao-toracica.png",
    arquivoSugerido: "percussao-toracica.png",
    prioridade: "media",
  },

  // =========================================================================
  // 9. PRECÓRDIO CARDIOVASCULAR
  // =========================================================================
  "precordio_cardiovascular:inspecionar_precordio": {
    regiaoId: "precordio_cardiovascular",
    acaoId: "inspecionar_precordio",
    titulo: "Inspeção do precórdio",
    descricao: "Observe região anterior do tórax.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/precordio-cardiovascular/inspecao-precordio.png",
    arquivoSugerido: "inspecao-precordio.png",
    prioridade: "media",
  },
  "precordio_cardiovascular:palpar_precordio": {
    regiaoId: "precordio_cardiovascular",
    acaoId: "palpar_precordio",
    titulo: "Palpação do precórdio",
    descricao: "Localize o ictus cordis.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/precordio-cardiovascular/palpacao-precordio.png",
    arquivoSugerido: "palpacao-precordio.png",
    prioridade: "media",
  },
  "precordio_cardiovascular:avaliar_ictus": {
    regiaoId: "precordio_cardiovascular",
    acaoId: "avaliar_ictus",
    titulo: "Palpação do precórdio",
    descricao: "Localize o ictus cordis.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/precordio-cardiovascular/palpacao-precordio.png",
    arquivoSugerido: "palpacao-precordio.png",
    prioridade: "alta",
  },
  "precordio_cardiovascular:auscultar_foco_aortico": {
    regiaoId: "precordio_cardiovascular",
    acaoId: "auscultar_foco_aortico",
    titulo: "Focos de ausculta cardíaca",
    descricao: "Diagrama dos focos cardíacos.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/precordio-cardiovascular/focos-ausculta-cardiaca.png",
    arquivoSugerido: "focos-ausculta-cardiaca.png",
    prioridade: "alta",
  },
  "precordio_cardiovascular:auscultar_foco_pulmonar": {
    regiaoId: "precordio_cardiovascular",
    acaoId: "auscultar_foco_pulmonar",
    titulo: "Focos de ausculta cardíaca",
    descricao: "Diagrama dos focos cardíacos.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/precordio-cardiovascular/focos-ausculta-cardiaca.png",
    arquivoSugerido: "focos-ausculta-cardiaca.png",
    prioridade: "alta",
  },
  "precordio_cardiovascular:auscultar_foco_tricuspide": {
    regiaoId: "precordio_cardiovascular",
    acaoId: "auscultar_foco_tricuspide",
    titulo: "Focos de ausculta cardíaca",
    descricao: "Diagrama dos focos cardíacos.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/precordio-cardiovascular/focos-ausculta-cardiaca.png",
    arquivoSugerido: "focos-ausculta-cardiaca.png",
    prioridade: "alta",
  },
  "precordio_cardiovascular:auscultar_foco_mitral": {
    regiaoId: "precordio_cardiovascular",
    acaoId: "auscultar_foco_mitral",
    titulo: "Focos de ausculta cardíaca",
    descricao: "Diagrama dos focos cardíacos.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/precordio-cardiovascular/focos-ausculta-cardiaca.png",
    arquivoSugerido: "focos-ausculta-cardiaca.png",
    prioridade: "alta",
  },
  "precordio_cardiovascular:avaliar_bulhas": {
    regiaoId: "precordio_cardiovascular",
    acaoId: "avaliar_bulhas",
    titulo: "Focos de ausculta cardíaca",
    descricao: "Diagrama dos focos cardíacos.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/precordio-cardiovascular/focos-ausculta-cardiaca.png",
    arquivoSugerido: "focos-ausculta-cardiaca.png",
    prioridade: "alta",
  },
  "precordio_cardiovascular:avaliar_sopro": {
    regiaoId: "precordio_cardiovascular",
    acaoId: "avaliar_sopro",
    titulo: "Focos de ausculta cardíaca",
    descricao: "Diagrama dos focos cardíacos.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/precordio-cardiovascular/focos-ausculta-cardiaca.png",
    arquivoSugerido: "focos-ausculta-cardiaca.png",
    prioridade: "alta",
  },
  "precordio_cardiovascular:avaliar_ritmo_cardiaco": {
    regiaoId: "precordio_cardiovascular",
    acaoId: "avaliar_ritmo_cardiaco",
    titulo: "Focos de ausculta cardíaca",
    descricao: "Diagrama dos focos cardíacos.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/precordio-cardiovascular/focos-ausculta-cardiaca.png",
    arquivoSugerido: "focos-ausculta-cardiaca.png",
    prioridade: "alta",
  },
  "precordio_cardiovascular:avaliar_atrito_pericardico": {
    regiaoId: "precordio_cardiovascular",
    acaoId: "avaliar_atrito_pericardico",
    titulo: "Atrito pericárdico",
    descricao: "Som de fricção na pericardite.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/precordio-cardiovascular/atrito-pericardico.png",
    arquivoSugerido: "atrito-pericardico.png",
    prioridade: "media",
  },

  // =========================================================================
  // 10. PRESSÃO ARTERIAL
  // =========================================================================
  "pressao_arterial:escolher_manguito_adequado": {
    regiaoId: "pressao_arterial",
    acaoId: "escolher_manguito_adequado",
    titulo: "Escolha do manguito adequado",
    descricao: "Tamanho correto do manguito.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pressao-arterial/manguito-adequado.png",
    arquivoSugerido: "manguito-adequado.png",
    prioridade: "alta",
  },
  "pressao_arterial:posicionar_crianca_para_PA": {
    regiaoId: "pressao_arterial",
    acaoId: "posicionar_crianca_para_PA",
    titulo: "Posicionamento para aferição de PA",
    descricao: "Postura adequada.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pressao-arterial/posicionamento-afericao-pa.png",
    arquivoSugerido: "posicionamento-afericao-pa.png",
    prioridade: "alta",
  },
  "pressao_arterial:posicionar_braco_altura_coracao": {
    regiaoId: "pressao_arterial",
    acaoId: "posicionar_braco_altura_coracao",
    titulo: "Posicionamento para aferição de PA",
    descricao: "Postura adequada.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pressao-arterial/posicionamento-afericao-pa.png",
    arquivoSugerido: "posicionamento-afericao-pa.png",
    prioridade: "alta",
  },
  "pressao_arterial:aferir_pressao_arterial": {
    regiaoId: "pressao_arterial",
    acaoId: "aferir_pressao_arterial",
    titulo: "Posicionamento para aferição de PA",
    descricao: "Postura adequada.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pressao-arterial/posicionamento-afericao-pa.png",
    arquivoSugerido: "posicionamento-afericao-pa.png",
    prioridade: "alta",
  },
  "pressao_arterial:classificar_pressao_por_percentil": {
    regiaoId: "pressao_arterial",
    acaoId: "classificar_pressao_por_percentil",
    titulo: "Classificação de PA por percentil",
    descricao: "Uso de tabelas de referência.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pressao-arterial/classificacao-percentil-pa.png",
    arquivoSugerido: "classificacao-percentil-pa.png",
    prioridade: "alta",
  },

  // =========================================================================
  // 11. ABDOME
  // =========================================================================
  "abdome:inspecionar_abdome": {
    regiaoId: "abdome",
    acaoId: "inspecionar_abdome",
    titulo: "Inspeção do abdome",
    descricao: "Observe forma e características.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/abdome/inspecao-abdome.png",
    arquivoSugerido: "inspecao-abdome.png",
    prioridade: "alta",
  },
  "abdome:auscultar_ruidos_hidroaereos": {
    regiaoId: "abdome",
    acaoId: "auscultar_ruidos_hidroaereos",
    titulo: "Ausculta de ruídos hidroaéreos",
    descricao: "Avalie ruídos intestinais.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/abdome/ausculta-ruidos-hidroaereos.png",
    arquivoSugerido: "ausculta-ruidos-hidroaereos.png",
    prioridade: "alta",
  },
  "abdome:palpar_abdome": {
    regiaoId: "abdome",
    acaoId: "palpar_abdome",
    titulo: "Palpação abdominal",
    descricao: "Técnica de palpação.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/abdome/palpacao-abdominal.png",
    arquivoSugerido: "palpacao-abdominal.png",
    prioridade: "alta",
  },
  "abdome:avaliar_dor_abdominal": {
    regiaoId: "abdome",
    acaoId: "avaliar_dor_abdominal",
    titulo: "Avaliação de dor abdominal",
    descricao: "Localize dor e defesa.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/abdome/dor-defesa-abdominal.png",
    arquivoSugerido: "dor-defesa-abdominal.png",
    prioridade: "alta",
  },
  "abdome:avaliar_defesa": {
    regiaoId: "abdome",
    acaoId: "avaliar_defesa",
    titulo: "Avaliação de dor abdominal",
    descricao: "Localize dor e defesa.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/abdome/dor-defesa-abdominal.png",
    arquivoSugerido: "dor-defesa-abdominal.png",
    prioridade: "alta",
  },
  "abdome:percutir_abdome": {
    regiaoId: "abdome",
    acaoId: "percutir_abdome",
    titulo: "Percussão abdominal",
    descricao: "Observe sons de percussão.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/abdome/percussao-abdominal.png",
    arquivoSugerido: "percussao-abdominal.png",
    prioridade: "media",
  },

  // =========================================================================
  // 12. FÍGADO
  // =========================================================================
  "figado:palpar_figado": {
    regiaoId: "figado",
    acaoId: "palpar_figado",
    titulo: "Palpação hepática",
    descricao: "Técnica de palpação.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/figado/palpacao-figado-hepatomegalia.png",
    arquivoSugerido: "palpacao-figado-hepatomegalia.png",
    prioridade: "alta",
  },
  "figado:pesquisar_hepatomegalia": {
    regiaoId: "figado",
    acaoId: "pesquisar_hepatomegalia",
    titulo: "Palpação hepática",
    descricao: "Técnica de palpação.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/figado/palpacao-figado-hepatomegalia.png",
    arquivoSugerido: "palpacao-figado-hepatomegalia.png",
    prioridade: "alta",
  },
  "figado:medir_borda_hepatica": {
    regiaoId: "figado",
    acaoId: "medir_borda_hepatica",
    titulo: "Palpação hepática",
    descricao: "Técnica de palpação.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/figado/palpacao-figado-hepatomegalia.png",
    arquivoSugerido: "palpacao-figado-hepatomegalia.png",
    prioridade: "alta",
  },
  "figado:avaliar_consistencia_figado": {
    regiaoId: "figado",
    acaoId: "avaliar_consistencia_figado",
    titulo: "Palpação hepática",
    descricao: "Técnica de palpação.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/figado/palpacao-figado-hepatomegalia.png",
    arquivoSugerido: "palpacao-figado-hepatomegalia.png",
    prioridade: "media",
  },
  "figado:avaliar_dor_hepatica": {
    regiaoId: "figado",
    acaoId: "avaliar_dor_hepatica",
    titulo: "Palpação hepática",
    descricao: "Técnica de palpação.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/figado/palpacao-figado-hepatomegalia.png",
    arquivoSugerido: "palpacao-figado-hepatomegalia.png",
    prioridade: "media",
  },

  // =========================================================================
  // 13. BAÇO
  // =========================================================================
  "baco:palpar_baco": {
    regiaoId: "baco",
    acaoId: "palpar_baco",
    titulo: "Palpação esplênica",
    descricao: "Técnica de palpação.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/baco/palpacao-baco-esplenomegalia.png",
    arquivoSugerido: "palpacao-baco-esplenomegalia.png",
    prioridade: "alta",
  },
  "baco:pesquisar_esplenomegalia": {
    regiaoId: "baco",
    acaoId: "pesquisar_esplenomegalia",
    titulo: "Palpação esplênica",
    descricao: "Técnica de palpação.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/baco/palpacao-baco-esplenomegalia.png",
    arquivoSugerido: "palpacao-baco-esplenomegalia.png",
    prioridade: "alta",
  },
  "baco:avaliar_borda_esplenica": {
    regiaoId: "baco",
    acaoId: "avaliar_borda_esplenica",
    titulo: "Palpação esplênica",
    descricao: "Técnica de palpação.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/baco/palpacao-baco-esplenomegalia.png",
    arquivoSugerido: "palpacao-baco-esplenomegalia.png",
    prioridade: "alta",
  },

  // =========================================================================
  // 14. PELE E MUCOSAS
  // =========================================================================
  "pele_mucosas:avaliar_hidratacao": {
    regiaoId: "pele_mucosas",
    acaoId: "avaliar_hidratacao",
    titulo: "Hidratação das mucosas",
    descricao: "Observe turgor e umidade.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pele-mucosas/desidratacao-mucosas.png",
    arquivoSugerido: "desidratacao-mucosas.png",
    prioridade: "alta",
  },
  "pele_mucosas:avaliar_turgor_cutaneo": {
    regiaoId: "pele_mucosas",
    acaoId: "avaliar_turgor_cutaneo",
    titulo: "Hidratação das mucosas",
    descricao: "Observe turgor e umidade.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pele-mucosas/desidratacao-mucosas.png",
    arquivoSugerido: "desidratacao-mucosas.png",
    prioridade: "alta",
  },
  "pele_mucosas:avaliar_exantema": {
    regiaoId: "pele_mucosas",
    acaoId: "avaliar_exantema",
    titulo: "Exantema maculopapular",
    descricao: "Lesões cutâneas.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pele-mucosas/exantema-maculopapular.png",
    arquivoSugerido: "exantema-maculopapular.png",
    prioridade: "alta",
  },
  "pele_mucosas:avaliar_lesoes_elementares": {
    regiaoId: "pele_mucosas",
    acaoId: "avaliar_lesoes_elementares",
    titulo: "Exantema maculopapular",
    descricao: "Lesões cutâneas.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pele-mucosas/exantema-maculopapular.png",
    arquivoSugerido: "exantema-maculopapular.png",
    prioridade: "alta",
  },
  "pele_mucosas:avaliar_petequias": {
    regiaoId: "pele_mucosas",
    acaoId: "avaliar_petequias",
    titulo: "Petéquias",
    descricao: "Lesões puntiformes.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pele-mucosas/petequias.png",
    arquivoSugerido: "petequias.png",
    prioridade: "alta",
  },
  "pele_mucosas:avaliar_equimoses": {
    regiaoId: "pele_mucosas",
    acaoId: "avaliar_equimoses",
    titulo: "Equimoses",
    descricao: "Extravasamento sanguíneo.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pele-mucosas/equimoses.png",
    arquivoSugerido: "equimoses.png",
    prioridade: "alta",
  },
  "pele_mucosas:avaliar_hematomas": {
    regiaoId: "pele_mucosas",
    acaoId: "avaliar_hematomas",
    titulo: "Equimoses",
    descricao: "Extravasamento sanguíneo.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pele-mucosas/equimoses.png",
    arquivoSugerido: "equimoses.png",
    prioridade: "alta",
  },
  "pele_mucosas:avaliar_ictericia": {
    regiaoId: "pele_mucosas",
    acaoId: "avaliar_ictericia",
    titulo: "Icterícia",
    descricao: "Coloração amarelada.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pele-mucosas/ictericia.png",
    arquivoSugerido: "ictericia.png",
    prioridade: "alta",
  },
  "pele_mucosas:avaliar_palidez_cutanea": {
    regiaoId: "pele_mucosas",
    acaoId: "avaliar_palidez_cutanea",
    titulo: "Palidez cutânea",
    descricao: "Redução da vascularização.",
    tipo: "guia",
    prioridade: "media",
  },
  "pele_mucosas:avaliar_sinais_maus_tratos": {
    regiaoId: "pele_mucosas",
    acaoId: "avaliar_sinais_maus_tratos",
    titulo: "Sinais de abuso",
    descricao: "Lesões compatíveis com trauma.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pele-mucosas/sinais-maus-tratos.png",
    arquivoSugerido: "sinais-maus-tratos.png",
    prioridade: "alta",
  },

  // =========================================================================
  // 15. MEMBROS E PERFUSÃO
  // =========================================================================
  "membros_perfusao:avaliar_perfusao_periferica": {
    regiaoId: "membros_perfusao",
    acaoId: "avaliar_perfusao_periferica",
    titulo: "Avaliação de perfusão",
    descricao: "Avalie enchimento capilar.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/membros-perfusao/perfusao-tempo-enchimento-capilar.png",
    arquivoSugerido: "perfusao-tempo-enchimento-capilar.png",
    prioridade: "alta",
  },
  "membros_perfusao:avaliar_tempo_enchimento_capilar": {
    regiaoId: "membros_perfusao",
    acaoId: "avaliar_tempo_enchimento_capilar",
    titulo: "Avaliação de perfusão",
    descricao: "Avalie enchimento capilar.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/membros-perfusao/perfusao-tempo-enchimento-capilar.png",
    arquivoSugerido: "perfusao-tempo-enchimento-capilar.png",
    prioridade: "alta",
  },
  "membros_perfusao:palpar_pulsos_perifericos": {
    regiaoId: "membros_perfusao",
    acaoId: "palpar_pulsos_perifericos",
    titulo: "Palpação de pulsos",
    descricao: "Palpe pulsos periféricos.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/membros-perfusao/pulsos-perifericos.png",
    arquivoSugerido: "pulsos-perifericos.png",
    prioridade: "alta",
  },
  "membros_perfusao:avaliar_edema": {
    regiaoId: "membros_perfusao",
    acaoId: "avaliar_edema",
    titulo: "Avaliação de edema",
    descricao: "Localize edema.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/membros-perfusao/edema.png",
    arquivoSugerido: "edema.png",
    prioridade: "media",
  },
  "membros_perfusao:avaliar_baqueteamento_digital": {
    regiaoId: "membros_perfusao",
    acaoId: "avaliar_baqueteamento_digital",
    titulo: "Baqueteamento digital",
    descricao: "Alargamento de falanges.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/membros-perfusao/baqueteamento-digital.png",
    arquivoSugerido: "baqueteamento-digital.png",
    prioridade: "media",
  },
  "membros_perfusao:avaliar_cianose_extremidades": {
    regiaoId: "membros_perfusao",
    acaoId: "avaliar_cianose_extremidades",
    titulo: "Cianose periférica",
    descricao: "Coloração azulada.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/membros-perfusao/cianose-extremidades.png",
    arquivoSugerido: "cianose-extremidades.png",
    prioridade: "alta",
  },
  "membros_perfusao:avaliar_equimoses_membros": {
    regiaoId: "membros_perfusao",
    acaoId: "avaliar_equimoses_membros",
    titulo: "Equimoses em membros",
    descricao: "Extravasamento sanguíneo.",
    tipo: "imagem",
    src: "/images/pediatria/exames-interativos/pele-mucosas/equimoses.png",
    arquivoSugerido: "equimoses.png",
    prioridade: "media",
  },
  "membros_perfusao:avaliar_fraturas_deformidades": {
    regiaoId: "membros_perfusao",
    acaoId: "avaliar_fraturas_deformidades",
    titulo: "Avaliação de fraturas",
    descricao: "Inspecione deformidades.",
    tipo: "guia",
    prioridade: "media",
  },
};

export function obterMidiaExamePediatrico(
  regiaoId: string,
  acaoId: string
): MidiaExamePediatrico | null {
  const chave = `${regiaoId}:${acaoId}`;
  return MIDIAS_EXAME_PEDIATRICO[chave] ?? null;
}

export function obterTodasAsMidias(): MidiaExamePediatrico[] {
  return Object.values(MIDIAS_EXAME_PEDIATRICO);
}

export function obterMidiasPorRegiao(regiaoId: string): MidiaExamePediatrico[] {
  return Object.values(MIDIAS_EXAME_PEDIATRICO).filter((m) => m.regiaoId === regiaoId);
}
