// ============================================================================
// Casos OSCE Dinâmicos — Beta · PULSE ACTION MAP (Fase 2.5)
// ----------------------------------------------------------------------------
// Mapeamento CONCEITUAL de intervenções MEDIX → ações Pulse FUTURAS. Nenhuma
// execução: apenas nomes de ações do engine (PatientAction/EquipmentAction) e
// alvos fisiológicos esperados. Cobre as intervenções do contrato e os
// InterventionId reais do motor rule-based.
// ============================================================================

export interface PulseActionEntry {
  medixActionId: string;
  label: string;
  clinicalCategory: "suporte" | "medicacao" | "procedimento" | "ventilacao" | "monitorizacao" | "decisao";
  /** Ação(ões) candidata(s) no Pulse (nome do engine). "" quando não há suporte direto. */
  pulseActionCandidate: string;
  directPulseSupport: boolean;
  requiresTranslator: boolean;
  expectedPhysiologyTargets: string[];
  notes: string;
}

export const PULSE_ACTION_MAP: Record<string, PulseActionEntry> = {
  oxigenio: {
    medixActionId: "oxigenio",
    label: "Oxigênio suplementar",
    clinicalCategory: "suporte",
    pulseActionCandidate: "PatientAction.SupplementalOxygen / EquipmentAction.NasalCannula",
    directPulseSupport: true,
    requiresTranslator: true,
    expectedPhysiologyTargets: ["OxygenSaturation", "FractionOfInspiredOxygen"],
    notes: "Alvo SpO₂ ≥ 92%.",
  },
  oxigenio_alto_fluxo: {
    medixActionId: "oxigenio_alto_fluxo",
    label: "Oxigênio de alto fluxo / não reinalante",
    clinicalCategory: "suporte",
    pulseActionCandidate: "PatientAction.SupplementalOxygen (NonRebreather) / EquipmentAction",
    directPulseSupport: true,
    requiresTranslator: true,
    expectedPhysiologyTargets: ["OxygenSaturation", "FractionOfInspiredOxygen"],
    notes: "FiO₂ mais alta que cânula.",
  },
  salbutamol: {
    medixActionId: "salbutamol",
    label: "Salbutamol (SABA)",
    clinicalCategory: "medicacao",
    pulseActionCandidate: "EquipmentAction.InhalerConfiguration (Albuterol) + ConsciousRespiration.UseInhaler",
    directPulseSupport: true,
    requiresTranslator: true,
    expectedPhysiologyTargets: ["BronchodilationLevel", "InspiratoryRespiratoryResistance", "RespirationRate"],
    notes: "Broncodilatação; FC pode subir.",
  },
  ipratropio: {
    medixActionId: "ipratropio",
    label: "Ipratrópio",
    clinicalCategory: "medicacao",
    pulseActionCandidate: "SubstanceBolus/Infusion (aproximação) — sem ação dedicada",
    directPulseSupport: false,
    requiresTranslator: true,
    expectedPhysiologyTargets: ["BronchodilationLevel", "ExpiratoryRespiratoryResistance"],
    notes: "Sem ação dedicada; modelar como efeito broncodilatador adicional.",
  },
  corticoide: {
    medixActionId: "corticoide",
    label: "Corticoide sistêmico",
    clinicalCategory: "medicacao",
    pulseActionCandidate: "SubstanceCompoundInfusion / SubstanceBolus",
    directPulseSupport: false,
    requiresTranslator: true,
    expectedPhysiologyTargets: [],
    notes: "Efeito tardio; conta como conduta correta, sem melhora imediata de vitais.",
  },
  sulfato_magnesio: {
    medixActionId: "sulfato_magnesio",
    label: "Sulfato de magnésio",
    clinicalCategory: "medicacao",
    pulseActionCandidate: "SubstanceBolus (Magnesium)",
    directPulseSupport: false,
    requiresTranslator: true,
    expectedPhysiologyTargets: ["BronchodilationLevel"],
    notes: "Resgate na crise refratária.",
  },
  "sulfato-magnesio": {
    medixActionId: "sulfato-magnesio",
    label: "Sulfato de magnésio (alias InterventionId)",
    clinicalCategory: "medicacao",
    pulseActionCandidate: "SubstanceBolus (Magnesium)",
    directPulseSupport: false,
    requiresTranslator: true,
    expectedPhysiologyTargets: ["BronchodilationLevel"],
    notes: "Alias do id do motor.",
  },
  descompressao_toracica: {
    medixActionId: "descompressao_toracica",
    label: "Descompressão torácica por agulha",
    clinicalCategory: "procedimento",
    pulseActionCandidate: "PatientAction.NeedleDecompression",
    directPulseSupport: true,
    requiresTranslator: false,
    expectedPhysiologyTargets: ["OxygenSaturation", "SystolicArterialPressure", "MeanArterialPressure"],
    notes: "Intervenção salvadora no pneumotórax hipertensivo.",
  },
  drenagem_toracica: {
    medixActionId: "drenagem_toracica",
    label: "Drenagem torácica (toracostomia)",
    clinicalCategory: "procedimento",
    pulseActionCandidate: "PatientAction.TubeThoracostomy",
    directPulseSupport: true,
    requiresTranslator: false,
    expectedPhysiologyTargets: ["OxygenSaturation", "TidalVolume"],
    notes: "Definitivo após descompressão.",
  },
  ventilacao_bvm: {
    medixActionId: "ventilacao_bvm",
    label: "Ventilação com bolsa-válvula-máscara",
    clinicalCategory: "ventilacao",
    pulseActionCandidate: "EquipmentAction.BagValveMask",
    directPulseSupport: true,
    requiresTranslator: true,
    expectedPhysiologyTargets: ["TidalVolume", "OxygenSaturation", "EndTidalCarbonDioxidePressure"],
    notes: "Suporte ventilatório manual.",
  },
  intubacao: {
    medixActionId: "intubacao",
    label: "Intubação orotraqueal",
    clinicalCategory: "procedimento",
    pulseActionCandidate: "PatientAction.Intubation",
    directPulseSupport: true,
    requiresTranslator: false,
    expectedPhysiologyTargets: ["TidalVolume", "OxygenSaturation"],
    notes: "Via aérea avançada.",
  },
  "intubacao-uti": {
    medixActionId: "intubacao-uti",
    label: "Intubação / UTI (alias InterventionId)",
    clinicalCategory: "procedimento",
    pulseActionCandidate: "PatientAction.Intubation + EquipmentAction.MechanicalVentilator",
    directPulseSupport: true,
    requiresTranslator: true,
    expectedPhysiologyTargets: ["TidalVolume", "OxygenSaturation", "ExtrinsicPositiveEndExpiratoryPressure"],
    notes: "Alias do id do motor.",
  },
  ventilacao_mecanica: {
    medixActionId: "ventilacao_mecanica",
    label: "Ventilação mecânica",
    clinicalCategory: "ventilacao",
    pulseActionCandidate: "EquipmentAction.MechanicalVentilator",
    directPulseSupport: true,
    requiresTranslator: true,
    expectedPhysiologyTargets: ["TidalVolume", "ExtrinsicPositiveEndExpiratoryPressure", "OxygenSaturation", "HorowitzIndex"],
    notes: "PEEP/pressões configuráveis.",
  },
  fluidos_suporte: {
    medixActionId: "fluidos_suporte",
    label: "Fluidos / reposição volêmica",
    clinicalCategory: "suporte",
    pulseActionCandidate: "PatientAction.SubstanceCompoundInfusion (Saline/Ringers)",
    directPulseSupport: true,
    requiresTranslator: true,
    expectedPhysiologyTargets: ["BloodVolume", "MeanArterialPressure", "CardiacOutput"],
    notes: "Choque hipovolêmico/desidratação.",
  },
  transfusao: {
    medixActionId: "transfusao",
    label: "Transfusão (hemocomponentes)",
    clinicalCategory: "suporte",
    pulseActionCandidate: "PatientAction.SubstanceCompoundInfusion (Blood/PackedRBC)",
    directPulseSupport: true,
    requiresTranslator: true,
    expectedPhysiologyTargets: ["BloodVolume", "HemoglobinContent", "MeanArterialPressure"],
    notes: "Cenários HemorrhageClass*PackedRBC.",
  },
  vasopressor: {
    medixActionId: "vasopressor",
    label: "Vasopressor",
    clinicalCategory: "medicacao",
    pulseActionCandidate: "PatientAction.SubstanceInfusion (Norepinephrine)",
    directPulseSupport: true,
    requiresTranslator: true,
    expectedPhysiologyTargets: ["MeanArterialPressure", "SystolicArterialPressure", "HeartRate"],
    notes: "Suporte hemodinâmico (sepse/choque).",
  },
  antibiotico: {
    medixActionId: "antibiotico",
    label: "Antibiótico",
    clinicalCategory: "medicacao",
    pulseActionCandidate: "SubstanceBolus (aproximação) — sem modelo de infecção",
    directPulseSupport: false,
    requiresTranslator: true,
    expectedPhysiologyTargets: [],
    notes: "Conduta correta; efeito não fisiológico imediato no Pulse.",
  },
  analgesia: {
    medixActionId: "analgesia",
    label: "Analgesia",
    clinicalCategory: "medicacao",
    pulseActionCandidate: "SubstanceBolus (Morphine/Fentanyl)",
    directPulseSupport: true,
    requiresTranslator: true,
    expectedPhysiologyTargets: ["RespirationRate", "HeartRate"],
    notes: "Atenção à depressão respiratória.",
  },
  monitorizacao: {
    medixActionId: "monitorizacao",
    label: "Monitorização",
    clinicalCategory: "monitorizacao",
    pulseActionCandidate: "DataRequest (sem ação física)",
    directPulseSupport: true,
    requiresTranslator: false,
    expectedPhysiologyTargets: ["HeartRate", "RespirationRate", "OxygenSaturation"],
    notes: "Leitura contínua; não altera o estado.",
  },
  acesso_venoso: {
    medixActionId: "acesso_venoso",
    label: "Acesso venoso",
    clinicalCategory: "suporte",
    pulseActionCandidate: "(preparo — sem ação fisiológica no Pulse)",
    directPulseSupport: false,
    requiresTranslator: false,
    expectedPhysiologyTargets: [],
    notes: "Habilita infusões; sem efeito fisiológico próprio.",
  },
  solicitar_rx_torax: {
    medixActionId: "solicitar_rx_torax",
    label: "Solicitar RX de tórax",
    clinicalCategory: "monitorizacao",
    pulseActionCandidate: "AdvanceTime (espera) — sem intervenção",
    directPulseSupport: true,
    requiresTranslator: false,
    expectedPhysiologyTargets: ["OxygenSaturation", "SystolicArterialPressure"],
    notes: "No paciente instável, esperar o RX antes da descompressão piora a fisiologia.",
  },
  solicitar_usg_torax: {
    medixActionId: "solicitar_usg_torax",
    label: "USG torácico (beira-leito)",
    clinicalCategory: "monitorizacao",
    pulseActionCandidate: "(beira-leito — sem espera fisiológica relevante)",
    directPulseSupport: true,
    requiresTranslator: false,
    expectedPhysiologyTargets: [],
    notes: "Rápido; não atrasa a conduta.",
  },
  reavaliar: {
    medixActionId: "reavaliar",
    label: "Reavaliar",
    clinicalCategory: "monitorizacao",
    pulseActionCandidate: "AdvanceTime + DataRequest",
    directPulseSupport: true,
    requiresTranslator: false,
    expectedPhysiologyTargets: ["OxygenSaturation", "RespirationRate"],
    notes: "Avança tempo e relê os dados.",
  },
  internacao: {
    medixActionId: "internacao",
    label: "Internação",
    clinicalCategory: "decisao",
    pulseActionCandidate: "(decisão clínica — sem ação Pulse)",
    directPulseSupport: false,
    requiresTranslator: false,
    expectedPhysiologyTargets: [],
    notes: "Decisão de destino; avaliada pela rubrica.",
  },
  aguardar_exames: {
    medixActionId: "aguardar_exames",
    label: "Aguardar exames",
    clinicalCategory: "decisao",
    pulseActionCandidate: "AdvanceTime (sem intervenção)",
    directPulseSupport: true,
    requiresTranslator: false,
    expectedPhysiologyTargets: ["OxygenSaturation", "SystolicArterialPressure"],
    notes: "Em paciente instável, aguardar piora a fisiologia (erro crítico potencial).",
  },
  alta: {
    medixActionId: "alta",
    label: "Alta (alias InterventionId)",
    clinicalCategory: "decisao",
    pulseActionCandidate: "(decisão clínica — sem ação Pulse)",
    directPulseSupport: false,
    requiresTranslator: false,
    expectedPhysiologyTargets: [],
    notes: "Insegura se fisiologia ainda instável.",
  },
  alta_precoce: {
    medixActionId: "alta_precoce",
    label: "Alta precoce",
    clinicalCategory: "decisao",
    pulseActionCandidate: "(decisão clínica — sem ação Pulse)",
    directPulseSupport: false,
    requiresTranslator: false,
    expectedPhysiologyTargets: [],
    notes: "Erro crítico se critérios de alta não atingidos.",
  },

  // ---- Fase 4 — DPOC exacerbado ------------------------------------------
  oxigenio_controlado: {
    medixActionId: "oxigenio_controlado",
    label: "O₂ controlado (alvo 88–92%)",
    clinicalCategory: "suporte",
    pulseActionCandidate: "PatientAction.SupplementalOxygen (titulado) / EquipmentAction.VentilatorMask",
    directPulseSupport: true,
    requiresTranslator: true,
    expectedPhysiologyTargets: ["OxygenSaturation", "EndTidalCarbonDioxidePressure"],
    notes: "Teto de FiO₂ para manter SpO₂ 88–92%; evitar narcose por CO₂.",
  },
  oxigenio_alto_fluxo_sem_controle: {
    medixActionId: "oxigenio_alto_fluxo_sem_controle",
    label: "O₂ alto fluxo sem controle",
    clinicalCategory: "suporte",
    pulseActionCandidate: "PatientAction.SupplementalOxygen (NonRebreather, FiO₂ > 0,6)",
    directPulseSupport: true,
    requiresTranslator: true,
    expectedPhysiologyTargets: ["OxygenSaturation", "EndTidalCarbonDioxidePressure", "RespirationRate"],
    notes: "Erro clínico no DPOC: eleva SpO₂ acima do alvo, suprime drive hipóxico, agrava hipercápnia.",
  },
  ventilacao_nao_invasiva: {
    medixActionId: "ventilacao_nao_invasiva",
    label: "Ventilação não invasiva (VNI)",
    clinicalCategory: "ventilacao",
    pulseActionCandidate: "EquipmentAction.NonInvasiveVentilation / BiPAP",
    directPulseSupport: true,
    requiresTranslator: true,
    expectedPhysiologyTargets: [
      "TidalVolume",
      "RespirationRate",
      "EndTidalCarbonDioxidePressure",
      "OxygenSaturation",
    ],
    notes: "CPAP/BiPAP: reduz trabalho respiratório e melhora eliminação de CO₂.",
  },
  antibiotico_se_indicado: {
    medixActionId: "antibiotico_se_indicado",
    label: "Antibiótico (se indicado)",
    clinicalCategory: "medicacao",
    pulseActionCandidate: "SubstanceBolus (aproximação) — sem modelo de infecção no Pulse",
    directPulseSupport: false,
    requiresTranslator: true,
    expectedPhysiologyTargets: [],
    notes: "Indicado na exacerbação infecciosa; sem efeito fisiológico imediato no Pulse.",
  },
  sedativo_sem_indicacao: {
    medixActionId: "sedativo_sem_indicacao",
    label: "Sedativo sem indicação",
    clinicalCategory: "medicacao",
    pulseActionCandidate: "SubstanceBolus (Midazolam/Propofol)",
    directPulseSupport: true,
    requiresTranslator: true,
    expectedPhysiologyTargets: ["RespirationRate", "RespiratoryMusclePressure"],
    notes: "Erro crítico em DPOC com hipercápnia: suprime drive respiratório.",
  },
};

/** Busca o mapeamento de uma intervenção MEDIX. */

export function getPulseAction(medixActionId: string): PulseActionEntry | undefined {
  return PULSE_ACTION_MAP[medixActionId];
}
