import { ECGPattern } from './types'

export const PADROES_ECG: ECGPattern[] = [
  {
    id: 'ecg_pediatrico_normal',
    titulo: 'ECG Pediátrico Normal',
    frequenciaCardiaca: 110,
    ritmo: 'Sinusal regular',
    eixo: 'Normal (+60° a +120°)',
    pr: '100-160 ms',
    qrs: '60-100 ms',
    qtc: '400 ms',
    achados: [
      { derivacao: 'Geral', achado: 'Sem alterações' },
      { derivacao: 'Ritmo', achado: 'Sinusal regular, frequência apropriada para idade' },
    ],
    laudo: 'ECG pediátrico normal. Ritmo sinusal regular compatível com idade. Sem alterações de repolarização.',
    derivacoesComSupra: [],
    derivacoesComInfra: [],
    derivacoesComInversaoT: [],
    derivacoesComQPatologica: [],
    observacoesClinicas: ['ECG normal de repouso no lactente'],
    imagem: '/images/ecg/pediatrico_normal.png',
  },
  {
    id: 'taquicardia_sinusal',
    titulo: 'Taquicardia Sinusal',
    frequenciaCardiaca: 150,
    ritmo: 'Sinusal regular',
    eixo: 'Normal',
    pr: '100 ms',
    qrs: '70 ms',
    qtc: '390 ms',
    achados: [
      { derivacao: 'Geral', achado: 'Frequência cardíaca elevada para a idade' },
      { derivacao: 'Ritmo', achado: 'Sinusal regular, taquicárdico' },
    ],
    laudo: 'Taquicardia sinusal com ritmo regular. Frequência cardíaca elevada para idade pediátrica.',
    derivacoesComSupra: [],
    derivacoesComInfra: [],
    derivacoesComInversaoT: [],
    derivacoesComQPatologica: [],
    observacoesClinicas: ['Investigar causa: febre, dor, desidratação, insuficiência cardíaca'],
    imagem: '/images/ecg/taquicardia_sinusal.png',
  },
  {
    id: 'bradicardia_sinusal',
    titulo: 'Bradicardia Sinusal',
    frequenciaCardiaca: 60,
    ritmo: 'Sinusal regular',
    eixo: 'Normal',
    pr: '120 ms',
    qrs: '75 ms',
    qtc: '420 ms',
    achados: [
      { derivacao: 'Geral', achado: 'Frequência cardíaca reduzida para a idade' },
      { derivacao: 'Ritmo', achado: 'Sinusal regular, bradicárdico' },
    ],
    laudo: 'Bradicardia sinusal com ritmo regular. Frequência cardíaca reduzida para idade pediátrica.',
    derivacoesComSupra: [],
    derivacoesComInfra: [],
    derivacoesComInversaoT: [],
    derivacoesComQPatologica: [],
    observacoesClinicas: ['Treinar atleta, hipotireoidismo, aumento de pressão intracraniana'],
    imagem: '/images/ecg/bradicardia_sinusal.png',
  },
  {
    id: 'taquicardia_supraventricular',
    titulo: 'Taquicardia Supraventricular',
    frequenciaCardiaca: 220,
    ritmo: 'Regular',
    eixo: 'Normal',
    pr: 'Difícil visualizar (onda P em T)',
    qrs: '80 ms',
    qtc: '350 ms',
    achados: [
      { derivacao: 'Geral', achado: 'Taquicardia regular de QRS estreito' },
      { derivacao: 'Geral', achado: 'Frequência muito elevada (>200 bpm)' },
    ],
    laudo: 'Taquicardia supraventricular com complexos QRS estreitos. Frequência regular e muito elevada compatível com TSVP.',
    derivacoesComSupra: [],
    derivacoesComInfra: [],
    derivacoesComInversaoT: [],
    derivacoesComQPatologica: [],
    observacoesClinicas: ['Manobra de Valsalva, adenosina IV, avaliação de via acessória'],
    imagem: '/images/ecg/taquicardia_supraventricular.png',
  },
  {
    id: 'bloqueio_av_1_grau',
    titulo: 'Bloqueio AV de 1º Grau',
    frequenciaCardiaca: 100,
    ritmo: 'Sinusal',
    eixo: 'Normal',
    pr: '200 ms',
    qrs: '80 ms',
    qtc: '410 ms',
    achados: [
      { derivacao: 'Geral', achado: 'Intervalo PR prolongado' },
      { derivacao: 'Geral', achado: 'Condução AV 1:1 preservada' },
    ],
    laudo: 'Bloqueio atrioventricular de primeiro grau. Intervalo PR prolongado com condução atrioventricular preservada.',
    derivacoesComSupra: [],
    derivacoesComInfra: [],
    derivacoesComInversaoT: [],
    derivacoesComQPatologica: [],
    observacoesClinicas: ['Reumatismo cardíaco, cardiopatia congênita, medicações digitálicas'],
    imagem: '/images/ecg/bloqueio_av_1_grau.png',
  },
  {
    id: 'bloqueio_av_total',
    titulo: 'Bloqueio AV Total',
    frequenciaCardiaca: 50,
    ritmo: 'Dissociação AV',
    eixo: 'Normal',
    pr: 'Variável (dissociação)',
    qrs: '100 ms',
    qtc: '440 ms',
    achados: [
      { derivacao: 'Geral', achado: 'Dissociação atrioventricular completa' },
      { derivacao: 'Geral', achado: 'Ritmo atrial e ventricular independentes' },
    ],
    laudo: 'Bloqueio atrioventricular total com dissociação completa. Ritmo atrial e ventricular independentes.',
    derivacoesComSupra: [],
    derivacoesComInfra: [],
    derivacoesComInversaoT: [],
    derivacoesComQPatologica: [],
    observacoesClinicas: ['Indicação de marcapasso, bloqueio congênito de nascimento'],
    imagem: '/images/ecg/bloqueio_av_total.png',
  },
  {
    id: 'sobrecarga_ventricular_direita',
    titulo: 'Sobrecarga Ventricular Direita',
    frequenciaCardiaca: 120,
    ritmo: 'Sinusal',
    eixo: 'Desvio para direita',
    pr: '110 ms',
    qrs: '95 ms',
    qtc: '410 ms',
    achados: [
      { derivacao: 'V1', achado: 'Onda R proeminente (rsr\' ou R dominante)' },
      { derivacao: 'DIII, aVF', achado: 'Inversão de onda T' },
    ],
    laudo: 'Padrão sugestivo de sobrecarga ventricular direita. Eixo desviado à direita com alterações de V1.',
    derivacoesComSupra: [],
    derivacoesComInfra: [],
    derivacoesComInversaoT: ['V1', 'V2', 'DIII'],
    derivacoesComQPatologica: [],
    observacoesClinicas: ['Cardiopatia congênita (CIA, CIV), hipertensão pulmonar, asma crônica'],
    imagem: '/images/ecg/sobrecarga_vd.png',
  },
  {
    id: 'sobrecarga_ventricular_esquerda',
    titulo: 'Sobrecarga Ventricular Esquerda',
    frequenciaCardiaca: 100,
    ritmo: 'Sinusal',
    eixo: 'Desvio para esquerda',
    pr: '130 ms',
    qrs: '100 ms',
    qtc: '430 ms',
    achados: [
      { derivacao: 'V5-V6, DI, aVL', achado: 'Voltagem aumentada' },
      { derivacao: 'V5-V6, DI, aVL', achado: 'Inversão de onda T (strain)' },
    ],
    laudo: 'Critérios de sobrecarga ventricular esquerda com voltagem aumentada e inversão de T lateral.',
    derivacoesComSupra: [],
    derivacoesComInfra: [],
    derivacoesComInversaoT: ['V5', 'V6', 'DI', 'aVL'],
    derivacoesComQPatologica: [],
    observacoesClinicas: ['Coartação de aorta, estenose aórtica, hipertensão sistêmica'],
    imagem: '/images/ecg/sobrecarga_ve.png',
  },
  {
    id: 'hipertrofia_biventricular',
    titulo: 'Hipertrofia Biventricular',
    frequenciaCardiaca: 110,
    ritmo: 'Sinusal',
    eixo: 'Normal a desviado',
    pr: '120 ms',
    qrs: '105 ms',
    qtc: '420 ms',
    achados: [
      { derivacao: 'Geral', achado: 'Sinais de aumento de forças direita e esquerda' },
      { derivacao: 'V1', achado: 'Onda R e S aumentadas' },
    ],
    laudo: 'Padrão sugestivo de hipertrofia biventricular com critérios de ambas as câmaras.',
    derivacoesComSupra: [],
    derivacoesComInfra: [],
    derivacoesComInversaoT: ['V1', 'V2'],
    derivacoesComQPatologica: [],
    observacoesClinicas: ['Cardiopatia complexa, shunt intracardíaco, doença pulmonar crônica'],
    imagem: '/images/ecg/hipertrofia_biventricular.png',
  },
  {
    id: 'pericardite_aguda_pediatrica',
    titulo: 'Pericardite Aguda',
    frequenciaCardiaca: 110,
    ritmo: 'Sinusal',
    eixo: 'Normal',
    pr: '130 ms',
    qrs: '80 ms',
    qtc: '410 ms',
    achados: [
      { derivacao: 'Difuso', achado: 'Supradesnivelamento de ST concâvo' },
      { derivacao: 'Difuso', achado: 'Infradesnivelamento de PR' },
    ],
    laudo: 'Supradesnivelamento de ST difuso e infradesnivelamento de PR compatíveis com pericardite aguda.',
    derivacoesComSupra: ['DI', 'DII', 'V3', 'V4', 'V5', 'V6'],
    derivacoesComInfra: [],
    derivacoesComInversaoT: [],
    derivacoesComQPatologica: [],
    observacoesClinicas: ['Dor torácica, atrito pericárdico, ecocardiografia para derrame'],
    imagem: '/images/ecg/pericardite_aguda.png',
  },
  {
    id: 'miocardite',
    titulo: 'Miocardite',
    frequenciaCardiaca: 130,
    ritmo: 'Sinusal ou irregular',
    eixo: 'Normal',
    pr: '140 ms',
    qrs: '90 ms',
    qtc: '420 ms',
    achados: [
      { derivacao: 'Múltiplas', achado: 'Alterações inespecíficas de ST-T' },
      { derivacao: 'Precordiais', achado: 'Inversão de onda T, infra ST' },
    ],
    laudo: 'Alterações inespecíficas de ST-T sugestivas de miocardite. Pode haver arritmias associadas.',
    derivacoesComSupra: [],
    derivacoesComInfra: [],
    derivacoesComInversaoT: ['V2', 'V3', 'V4'],
    derivacoesComQPatologica: [],
    observacoesClinicas: ['Troponina elevada, ecocardiografia para disfunção, repouso'],
    imagem: '/images/ecg/miocardite.png',
  },
  {
    id: 'hipercalemia',
    titulo: 'Hipercalemia — Ondas T Apiculadas',
    frequenciaCardiaca: 105,
    ritmo: 'Sinusal',
    eixo: 'Normal',
    pr: '120 ms',
    qrs: '90 ms',
    qtc: '380 ms',
    achados: [
      { derivacao: 'Múltiplas', achado: 'Ondas T altas e apiculadas' },
      { derivacao: 'Geral', achado: 'QT encurtado' },
    ],
    laudo: 'Ondas T altas e apiculadas com QT encurtado, compatível com hipercalemia.',
    derivacoesComSupra: [],
    derivacoesComInfra: [],
    derivacoesComInversaoT: [],
    derivacoesComQPatologica: [],
    observacoesClinicas: ['Doença renal crônica, rabdomiólise, medicações (IECA)'],
    imagem: '/images/ecg/hipercalemia.png',
  },
  {
    id: 'qt_longo_congenito',
    titulo: 'QT Longo Congênito',
    frequenciaCardiaca: 100,
    ritmo: 'Sinusal',
    eixo: 'Normal',
    pr: '140 ms',
    qrs: '90 ms',
    qtc: '500 ms',
    achados: [
      { derivacao: 'Geral', achado: 'Intervalo QT prolongado para idade' },
      { derivacao: 'Múltiplas', achado: 'Possível inversão T, onda U proeminente' },
    ],
    laudo: 'Intervalo QTc prolongado compatível com síndrome de QT longo congênito. Risco de arritmias polimórficas.',
    derivacoesComSupra: [],
    derivacoesComInfra: [],
    derivacoesComInversaoT: ['V2', 'V3', 'V4'],
    derivacoesComQPatologica: [],
    observacoesClinicas: ['Síncope, morte súbita familiar, betabloqueadores, evitar gatilhos'],
    imagem: '/images/ecg/qt_longo.png',
  },
  {
    id: 'cia_padrao_sugestivo',
    titulo: 'Comunicação Interatrial — Padrão Sugestivo',
    frequenciaCardiaca: 110,
    ritmo: 'Sinusal',
    eixo: 'Desvio para direita',
    pr: '140 ms',
    qrs: '110 ms',
    qtc: '410 ms',
    achados: [
      { derivacao: 'V1-V2', achado: 'rSr\' — bloqueio incompleto de ramo direito' },
      { derivacao: 'DII, DIII, aVF', achado: 'Inversão de T simétrica' },
    ],
    laudo: 'Padrão sugestivo de comunicação interatrial com sobrecarga de câmaras direitas e BIRD.',
    derivacoesComSupra: [],
    derivacoesComInfra: [],
    derivacoesComInversaoT: ['V1', 'V2', 'DIII'],
    derivacoesComQPatologica: [],
    observacoesClinicas: ['Ecocardiografia para confirmação, seguimento cardiológico'],
    imagem: '/images/ecg/cia_padrao.png',
  },
  {
    id: 'tetralogia_fallot_padrao_sugestivo',
    titulo: 'Tetralogia de Fallot — Padrão Sugestivo',
    frequenciaCardiaca: 115,
    ritmo: 'Sinusal',
    eixo: 'Desvio para direita marcante',
    pr: '110 ms',
    qrs: '120 ms',
    qtc: '420 ms',
    achados: [
      { derivacao: 'V1-V2', achado: 'Onda R proeminente, onda S profunda em V6' },
      { derivacao: 'DII, DIII, aVF', achado: 'Inversão de T em derivações direitas' },
    ],
    laudo: 'Padrão sugestivo de tetralogia de Fallot com sobrecarga marcante de VD e desvio do eixo para direita.',
    derivacoesComSupra: [],
    derivacoesComInfra: [],
    derivacoesComInversaoT: ['V1', 'V2', 'V3', 'aVF'],
    derivacoesComQPatologica: [],
    observacoesClinicas: ['Cianose, hipoxemia, ecocardiografia para confirmação, cirurgia'],
    imagem: '/images/ecg/tetralogia_fallot.png',
  },
]

export function obterPadrao(id: string): ECGPattern | undefined {
  return PADROES_ECG.find((p) => p.id === id)
}

export function listarPadroes(): ECGPattern[] {
  return PADROES_ECG
}
