import { ECGPattern } from './types'

export const PADROES_ECG: ECGPattern[] = [
  {
    id: 'normal',
    titulo: 'ECG Normal',
    frequenciaCardiaca: 72,
    ritmo: 'Sinusal regular',
    eixo: 'Normal (-30° a 90°)',
    pr: '120-200 ms',
    qrs: '80-120 ms',
    qtc: '< 440 ms',
    achados: [
      { derivacao: 'Geral', achado: 'Sem alterações' },
      { derivacao: 'Ritmo', achado: 'Sinusal regular' },
    ],
    laudo: 'ECG dentro dos limites normais. Ritmo sinusal regular. Sem alterações de repolarização.',
    derivacoesComSupra: [],
    derivacoesComInfra: [],
    derivacoesComInversaoT: [],
    derivacoesComQPatologica: [],
    observacoesClinicas: ['ECG normal de repouso'],
    imagem: '/images/ecg/01_ecg_normal.png',
  },
  {
    id: 'angina_estavel',
    titulo: 'Padrão de Angina Estável',
    frequenciaCardiaca: 72,
    ritmo: 'Sinusal regular',
    eixo: 'Normal',
    pr: '160 ms',
    qrs: '90 ms',
    qtc: '410 ms',
    achados: [
      { derivacao: 'Repouso', achado: 'ECG normal ou com alterações mínimas' },
      {
        derivacao: 'Durante prova de esforço',
        achado: 'Infradesnivelamento de ST',
      },
    ],
    laudo:
      'ECG de repouso pode estar normal. Alterações esperadas durante prova de esforço. Compatível com angina estável por lesão coronária fixa.',
    derivacoesComSupra: [],
    derivacoesComInfra: [],
    derivacoesComInversaoT: [],
    derivacoesComQPatologica: [],
    observacoesClinicas: [
      'Sintomas desencadeados por esforço, aliviados em repouso',
      'Prova de esforço para confirmação',
    ],
    imagem: '/images/ecg/02_angina_estavel.png',
  },
  {
    id: 'angina_instavel',
    titulo: 'Padrão de Angina Instável',
    frequenciaCardiaca: 88,
    ritmo: 'Sinusal',
    eixo: 'Normal',
    pr: '150 ms',
    qrs: '100 ms',
    qtc: '430 ms',
    achados: [
      { derivacao: 'V2-V5', achado: 'Infradesnivelamento transitório de ST' },
      { derivacao: 'Múltiplas derivações', achado: 'Inversão simétrica de T' },
    ],
    laudo:
      'Infradesnivelamento de ST e inversão de onda T em derivações precordiais. Sugestivo de angina instável com isquemia miocárdica.',
    derivacoesComSupra: [],
    derivacoesComInfra: ['V2', 'V3', 'V4', 'V5'],
    derivacoesComInversaoT: ['V2', 'V3', 'V4', 'V5'],
    derivacoesComQPatologica: [],
    observacoesClinicas: [
      'Risco intermediário-alto de eventos coronários',
      'Hospitalização recomendada',
      'Cinecoronariografia urgente',
    ],
    imagem: '/images/ecg/03_angina_instavel.png',
  },
  {
    id: 'iam_sem_supra',
    titulo: 'IAM sem Supradesnivelamento (NSTEMI)',
    frequenciaCardiaca: 82,
    ritmo: 'Sinusal',
    eixo: 'Normal',
    pr: '140 ms',
    qrs: '95 ms',
    qtc: '440 ms',
    achados: [
      { derivacao: 'V2-V4', achado: 'Infradesnivelamento de ST' },
      { derivacao: 'Múltiplas derivações', achado: 'Inversão de onda T' },
    ],
    laudo:
      'Infradesnivelamento de ST e inversão de onda T compatíveis com isquemia miocárdica subendocárdica. Sugestivo de NSTEMI.',
    derivacoesComSupra: [],
    derivacoesComInfra: ['V2', 'V3', 'V4'],
    derivacoesComInversaoT: ['V2', 'V3', 'V4', 'DI', 'aVL'],
    derivacoesComQPatologica: [],
    observacoesClinicas: [
      'Avaliar marcadores de necrose (troponina)',
      'Elevar vigilância clínica',
      'Angiocoronariografia recomendada',
    ],
    imagem: '/images/ecg/04_iam_sem_supra_nstemi.png',
  },
  {
    id: 'iam_com_supra_inferior',
    titulo: 'IAM com SUPRA de ST Inferior',
    frequenciaCardiaca: 88,
    ritmo: 'Sinusal',
    eixo: 'Desvio para esquerda',
    pr: '160 ms',
    qrs: '100 ms',
    qtc: '450 ms',
    achados: [
      { derivacao: 'DII, DIII, aVF', achado: 'Supradesnivelamento de ST' },
      { derivacao: 'DI, aVL', achado: 'Infradesnivelamento de ST recíproco' },
    ],
    laudo:
      'Supradesnivelamento de ST em derivações inferiores (DII, DIII, aVF), compatível com infarto agudo inferior. Infradesnivelamento recíproco.',
    derivacoesComSupra: ['DII', 'DIII', 'aVF'],
    derivacoesComInfra: ['DI', 'aVL'],
    derivacoesComInversaoT: ['DII', 'DIII', 'aVF'],
    derivacoesComQPatologica: ['DII', 'DIII', 'aVF'],
    observacoesClinicas: [
      'Compatível com oclusão de artéria coronária direita',
      'Avaliar envolvimento de ventrículo direito',
      'Urgência: Intervenção coronária percutânea',
    ],
    imagem: '/images/ecg/05_iam_com_supra_inferior.png',
  },
  {
    id: 'iam_com_supra_anterior',
    titulo: 'IAM com SUPRA de ST Anterior',
    frequenciaCardiaca: 95,
    ritmo: 'Sinusal',
    eixo: 'Normal',
    pr: '150 ms',
    qrs: '110 ms',
    qtc: '460 ms',
    achados: [
      { derivacao: 'V1-V4', achado: 'Supradesnivelamento de ST' },
      { derivacao: 'DII, DIII, aVF', achado: 'Infradesnivelamento recíproco' },
    ],
    laudo:
      'Supradesnivelamento de ST em derivações precordiais anteriores (V1-V4), compatível com infarto agudo anterior. Infradesnivelamento recíproco inferior.',
    derivacoesComSupra: ['V1', 'V2', 'V3', 'V4'],
    derivacoesComInfra: ['DII', 'DIII', 'aVF'],
    derivacoesComInversaoT: ['V1', 'V2', 'V3', 'V4'],
    derivacoesComQPatologica: ['V1', 'V2', 'V3', 'V4'],
    observacoesClinicas: [
      'Oclusão de artéria interventricular anterior (AIA)',
      'Risco de insuficiência cardíaca e arritmias',
      'Urgência: Reperfusão imediata indicada',
    ],
    imagem: '/images/ecg/06_iam_com_supra_anterior.png',
  },
  {
    id: 'pericardite_aguda',
    titulo: 'Pericardite Aguda',
    frequenciaCardiaca: 85,
    ritmo: 'Sinusal',
    eixo: 'Normal',
    pr: '140 ms',
    qrs: '88 ms',
    qtc: '420 ms',
    achados: [
      {
        derivacao: 'Fase I (primeiras horas)',
        achado: 'Supradesnivelamento de ST difuso',
      },
      { derivacao: 'Fase I', achado: 'Infradesnivelamento de PR' },
      { derivacao: 'Fase II', achado: 'Retorno ao nível de base' },
    ],
    laudo:
      'Supradesnivelamento de ST difuso e infradesnivelamento de PR compatíveis com pericardite aguda em fase I. Sem alterações em derivações recíprocas.',
    derivacoesComSupra: ['DI', 'DII', 'V2', 'V3', 'V4', 'V5', 'V6'],
    derivacoesComInfra: [],
    derivacoesComInversaoT: [],
    derivacoesComQPatologica: [],
    observacoesClinicas: [
      'Dor torácica pleurítica aliviada ao inclinar-se para frente',
      'Atrito pericárdico ao exame',
      'Ecocardiografia para avaliar derrame',
    ],
    imagem: '/images/ecg/07_pericardite_aguda.png',
  },
  {
    id: 'fibrilacao_atrial',
    titulo: 'Fibrilação Atrial',
    frequenciaCardiaca: 120,
    ritmo: 'Irregular',
    eixo: 'Normal',
    pr: 'Não visível (F-F irregular)',
    qrs: '90 ms',
    qtc: '380 ms',
    achados: [
      { derivacao: 'Geral', achado: 'Linha de base irregular com ondas f' },
      { derivacao: 'Geral', achado: 'Complexos QRS irregulares' },
      { derivacao: 'V1', achado: 'Onda P substituída por onda f' },
    ],
    laudo:
      'Fibrilação atrial com resposta ventricular rápida. Ritmo completamente irregular. Ausência de ondas P distintas.',
    derivacoesComSupra: [],
    derivacoesComInfra: [],
    derivacoesComInversaoT: [],
    derivacoesComQPatologica: [],
    observacoesClinicas: [
      'Risco aumentado de acidente vascular cerebral',
      'Anticoagulação recomendada',
      'Controle da frequência cardíaca necessário',
    ],
    imagem: '/images/ecg/08_fibrilacao_atrial.png',
  },
  {
    id: 'tep_sobrecarga_direita',
    titulo: 'Tromboembolismo Pulmonar - Sobrecarga de VD',
    frequenciaCardiaca: 110,
    ritmo: 'Sinusal taquicárdico',
    eixo: 'Desvio para direita',
    pr: '120 ms',
    qrs: '120 ms',
    qtc: '410 ms',
    achados: [
      { derivacao: 'V1-V3', achado: 'Infradesnivelamento de ST' },
      { derivacao: 'DIII', achado: 'Inversão de onda T' },
      { derivacao: 'S1Q3T3', achado: 'Padrão clássico (quando presente)' },
    ],
    laudo:
      'Taquicardia sinusal com desvio do eixo para direita. Infradesnivelamento de ST em V1-V3 com inversão de T em DIII. Compatível com sobrecarga VD por TEP.',
    derivacoesComSupra: [],
    derivacoesComInfra: ['V1', 'V2', 'V3', 'DIII'],
    derivacoesComInversaoT: ['DIII', 'V1', 'V2'],
    derivacoesComQPatologica: [],
    observacoesClinicas: [
      'Dispneia aguda e dor torácica pleurítica',
      'Angio-TC de pulmão urgente',
      'Avaliação de risco para trombose',
    ],
    imagem: '/images/ecg/09_tep_sobrecarga_vd.png',
  },
  {
    id: 'hve_has',
    titulo: 'Hipertrofia Ventricular Esquerda (HVE) - HAS',
    frequenciaCardiaca: 95,
    ritmo: 'Sinusal',
    eixo: 'Desvio para esquerda',
    pr: '160 ms',
    qrs: '110 ms',
    qtc: '450 ms',
    achados: [
      {
        derivacao: 'DI, aVL, V5, V6',
        achado: 'Voltagem aumentada (critério de Sokolow)',
      },
      { derivacao: 'DI, aVL, V5, V6', achado: 'Inversão de onda T (strain)' },
      { derivacao: 'V1-V2', achado: 'Onda S profunda' },
    ],
    laudo:
      'Hipertrofia ventricular esquerda com padrão de strain. Voltagem aumentada em derivações laterais com inversão de T.',
    derivacoesComSupra: [],
    derivacoesComInfra: [],
    derivacoesComInversaoT: ['DI', 'aVL', 'V5', 'V6'],
    derivacoesComQPatologica: [],
    observacoesClinicas: [
      'Pressão arterial elevada cronicamente',
      'Avaliar para hipertensão secundária',
      'Investigar lesão de órgão-alvo',
      'Ecocardiografia para avaliar função sistólica',
    ],
    imagem: '/images/ecg/10_hve_has.png',
  },
]

export function obterPadrao(id: string): ECGPattern | undefined {
  return PADROES_ECG.find((p) => p.id === id)
}

export function listarPadroes(): ECGPattern[] {
  return PADROES_ECG
}
